### ISSUE TITLE
requestLayout() improperly called by android.widget.TextView

### ISSUE THREAD

**Issue by brycematsuda** [the-blue-alliance/the-blue-alliance-android#135]
logcat screams this *a lot* when loading the giant list of teams. Spamming tabs also causes more screaming and noticeable stuttering/lag. StackOverflow gives a lot of varying/irrelevant answers, but I'm guessing it has something to do with the creation of the cursor.

``06-17 21:09:10.567  32731-32731/com.thebluealliance.androidclient.development W/View﹕ requestLayout() improperly called by android.widget.TextView{426dbcb8 V.ED.... ......ID 0,0-214,38 #7f0a0054 app:id/team_name} during layout: running second layout pass``

``06-17 21:09:10.567  32731-32731/com.thebluealliance.androidclient.development W/View﹕ requestLayout() improperly called by android.widget.TextView{426dc108 V.ED.... ......ID 0,38-210,76 #7f0a0058 app:id/team_location} during layout: running second layout pass``

**Comment by nwalters512** [comment]
We no longer use cursors to display the main team list, so this is no longer an issue.
