### ISSUE TITLE
Animate scrolling of tabs

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#266]
The new implementation of tabs doesn't feel as smooth as it should, mainly when scrolling to tabs by touching the tab label (this is hard to put into words, but you'll see what I mean when you use the app). We should have the tab strip smoothly animate to the next selected tab; now that we have full control over the source code of it, this should be easier to do.

**Comment by phil-lopreiato** [comment]
Fixed somewhere in 5.0 update
