### ISSUE TITLE
Create Notification Dashboard

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#268]
Store the notifications that come in, and allow them to be shown all in one place. Continued from #264 - when the device has multiple notifications stacked together, it should open up this activity

**Comment by phil-lopreiato** [comment]
Plan:

This will need a new database table for ```notification_archive``` (I do like the idea of storing old notifications. Maybe have it clear on app update to manage size?). It'll need: ```notification_type```, ```title```, ```body```, ```intent```, ```received_time```, ```read```(maybe). 

It'll be a pretty simple listview to just show this table and open old notifications. We won't need to store some types, like ```PING``` and ```BROADCAST```

**Comment by nwalters512** [comment]
I wouldn't say clear on update, we should give the user control of that.
Maybe allow them to limit it to a fixed size (say, 200 max at a time?).
We'll also have to design this to account for any future updates to the app
or the backend. Perhaps we should version notifications?

**Comment by phil-lopreiato** [comment]
A fixed limit it hard to implement (do you know of a SQL construct that allows a max number of rows?), which is why I liked app update - it provides a deterministic point to clear the table. 

The parameters I picked above should be constant over the different versions of notifications (it's basically what gets displayed to the user), so I'm not totally sold it was necessary.

**Comment by nwalters512** [comment]
Fair enough regarding versioning. As for limiting the size, that wouldn't
be hard to do manually. When doing an insert, just check if that'll push
you over the limit. If it does, delete any extra rows. Regardless, I'm
still not in favor of deleting *anything* on behalf of the user, whether or
not we feel as devs that it makes sense.

**Comment by phil-lopreiato** [comment]
That's a fair point. The performance shouldn't matter too much, since the phone is already being broken to process the notification. I also we can make it pretty clear it's a temporary archive (last 200 received, or whatever) so deleting records as they go over the limit should be okay.

I've got to try and get this written this weekend, because it's got to be there when competitions start, otherwise flooding could happen again. It shouldn't be too hard, though
