### ISSUE TITLE
Summarize notifications, InboxStyle

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#272]
I turned on notifications for MadTown Throwdown match results. They must've just got their FMS connected to the internet since TBA suddenly poured in 50 notifications.

It should only chime once and combine the news into a summary InboxStyle notification.

http://developer.android.com/design/patterns/notifications.html#summarize_your_notifications

**Comment by phil-lopreiato** [comment]
This will be solved when #268 gets implemented (soon). We will summarize incoming notifications (by type? all together?) and have that notification open the dashboard.

**Comment by nwalters512** [comment]
All together makes the most sense. That way, we don't have to worry about
which notifications to dismiss or not when the dashboard is opened.

**Comment by phil-lopreiato** [comment]
Agreed.
