### ISSUE TITLE
Add "settings" icon to each row in myTBA

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#283]
We should put an option to go straight to the settings of a particular model in each list item of the myTBA lists. That would be easy to implement: just have an activity that contains a ```NotificationSettingsFragment```. This makes it easy for the user to just straight to the settings if they want to unfavorite/check subscription status/etc. It probably goes without saying, but we can use the gear icon for this.

**Comment by phil-lopreiato** [comment]
Fixed in 1133d1fbdfc93c381039131b76d8887ff775a1a3 (I think)
