### ISSUE TITLE
Figure out what to do with the FAB

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#285]
On the "info" pages of most models, there is a FAB that opens the fav/sub interface. However, when the content is tall enough, the FAB can cover portions of it. We have a few options in this case:

a) add some padding or a blank view to the bottom of every list
b) hide the FAB when you scroll down

I like option A, because we could probably make an adapter to do that for us. B also wouldn't work if the content is just slightly shorter than the height of the screen, because then the view wouldn't be scrollable and you couldn't hide the FAB. Any thoughts on this?

**Comment by phil-lopreiato** [comment]
FAB hidden on scroll in 5.0 update
