### ISSUE TITLE
Profile picture doesn't load on first activity creation

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#296]
If you start the app from a cold state (not backgrounded, no tasks running),the profile picture in the nav drawer doesn't load. It will load on any subsequent activity creations (child activities, home activity recreated after orientation change), but it refuses to load on the first activity creation, even after being cached. The cover photo, however, does load.

**Comment by phil-lopreiato** [comment]
This doesn't seem to be happening anymore. Can't reproduce from cold start (after force stop and clear from recents). Guess it's okay.

**Comment by phil-lopreiato** [comment]
Seems to be happening again. Still can't trace it

**Comment by phil-lopreiato** [comment]
This seems to have gone away again. Haven't seen it at all in v2.1.3. We can reopen if we need to
