### ISSUE TITLE
Q: Android FTC app based off The Blue Alliance app?

### ISSUE THREAD

**Issue by wgardnerg** [the-blue-alliance/the-blue-alliance-android#304]
Hi,

I'm interested in creating a Blue-Alliance-like app for FTC.  I know that FIRST doesn't release a lot of FTC match data (or any for this season, apparently), but complete team and event lists are accessible from the FIRST website.  Ideally, an android app would exist that allows a user to enter team and match data for a tournament locally, compute local OPR, CCWM type stats for scouting, etc. and store results in a local database on the android device.  Down the road in a dream world, FIRST and/or users could possibly upload data into a centralized database like what The Blue Alliance has achieved for FRC.

Question: it seems like I could start with the Blue Alliance android app and modify it for FTC.  Any advice on this?  Good idea or bad idea?  Should this be separate from The Blue Alliance or in some way integrated/ forked?

Thanks in advance for any advice y'all can provide,
Bill Gardner
cheer4ftc.blogspot.com

**Comment by nwalters512** [comment]
You certainly could use TBA as a starting point, but I'm not sure what
advantage that would give you. TBA is very dependent on and very integrated
with our API, of which there is no equivalent that I know of for FTC. You'd
have to build your own scraper to get info from the FIRST site, design your
own API to serve that info, and host a service that can serve up data from
requests. All that is easier said than done. It may make more sense to
start from scratch with an app that you can tightly integrate with your own
API.
