### ISSUE TITLE
2.0.16 Crash

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#310]
Reported on https://github.com/the-blue-alliance/the-blue-alliance/pull/1119#issuecomment-72580744

**Comment by phil-lopreiato** [comment]
@first3234, when you say "the subscription thing crashed" does the app itself crash? Can you hit "Report" and so you can send us a stack trace to fix it? What specific app version are you running?

**Comment by first3234** [comment]
version 2.0.16 of the app and when i went to see if the events i  subscribed too were still there and nothing and then shortly after it crashed but i am now checking to see if it does it again

**Comment by phil-lopreiato** [comment]
Did you subscribe to the "firehose" of all this year's events (which is what the pull request you originally commented on was for), or is this an unrelated issue?

**Comment by first3234** [comment]
what do you mean by "firehose"

**Comment by phil-lopreiato** [comment]
You haven't then. It's a feature that allows you to subscribe to all events in a year for automated services (for example, FRC Mega can use it). Don't worry about it - I was just confused because you posted your crash on the pull request for that code, so I thought they were related. Now I see it's just a regular crash.

If you can reproduce it, please submit the crash report (or capture a stack trace) and let me know, and I'll fix it.

**Comment by first3234** [comment]
ok i will as soon as it happens i will

**Comment by phil-lopreiato** [comment]
I believe this has been reproduced and closed in #317
