### ISSUE TITLE
Default header in nav drawer

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#312]
The default header image in the nav drawer that appears when the user isn't signed into MyTBA should probably be something TBA themed instead of the default colored paper.

**Comment by phil-lopreiato** [comment]
What if we did a subdued version of the background [here](https://github.com/the-blue-alliance/the-blue-alliance-logo/blob/master/tba_blue_full.pdf)

**Comment by nwalters512** [comment]
Fixed in #631
