### ISSUE TITLE
Current Weak Empty Again

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#322]
Need to fix up week detection, it seems

**Comment by fangeugene** [comment]
It was working yesterday and showed preseason.

**Comment by phil-lopreiato** [comment]
It's Sunday, so it's a new week, so I'm guessing that caused it to happen. I'm just going to get rid of the 'Current Week' label - I think an auto selected Week # will be fine. It was the different label that was causing the content to not be there (lack of key in the hashmap storing all events).

**Comment by phil-lopreiato** [comment]
![device](https://cloud.githubusercontent.com/assets/2754863/6204211/789cc074-b510-11e4-9d0b-3e250a6114d5.png)
