### ISSUE TITLE
"Save favorites" check mark stays green after success

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#331]
Steps to reproduce:
1. Open a model
2. Open the fav/sub interface, change something, click accept
3. On success, the check mark turns green and the screen closes
4. Reopen the fav/sub interface. The check mark is still green.

It should be reset to yellow when opening the interface.

**Comment by phil-lopreiato** [comment]
Fixed in 75cc73b2d00a8574ff41b00584b7b40b8c52e3d8
