### ISSUE TITLE
Rounding in Rankings

### ISSUE THREAD

**Issue by TheBassett** [the-blue-alliance/the-blue-alliance-android#336]
I noticed the following small aesthetic error where ranking numbers (specifically qualification average) aren't being cut off or rounded after being calculated/before being displayed. I did a quick search through the issues, didn't seem to find anything about the error yet so I decided to post it here!

Here's a picture of the error (using app version 2.1.7, build branch "2015-comp-freeze"):
![screenshot_2015-02-27-23-28-16 1](https://cloud.githubusercontent.com/assets/7651738/6424860/e98cf886-bed8-11e4-86aa-a187b69d2f1f.png)

**Comment by phil-lopreiato** [comment]
Thanks for the report! This is the first year where ranking items have been nonintegers (in my memory, at least).

We're going to need to make these changes around [here](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/background/event/PopulateEventRankings.java#L106). Probably abstract the rank string creation out into a helper method, where we can do rounding.
