### ISSUE TITLE
Unresponsive Favorite Screen

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance-android#342]
Hey fellas. Having some issues with the favorites screen.

I went to an event (Kettering, but I don't think specifics matter), went to Teams, clicked 2337, clicked "Show Team", click the star, and got the favorites page. After checking a few boxes, I tried to hit the check mark, but nothing happened. 
![screenshot_2015-03-04-10-07-35](https://cloud.githubusercontent.com/assets/516458/6486118/b0f1d39e-c256-11e4-9ac3-515b759151c6.png)

After going back and trying to click the Star again to get back in to the interface, I was stuck on the Team screen
![screenshot_2015-03-04-10-07-47](https://cloud.githubusercontent.com/assets/516458/6486122/c11fc974-c256-11e4-8c8c-8f04e131dea6.png)

After going back (which didn't bring me back to the list of Kettering teams - it brought me to the list of all the teams 😓) I went back to 2337 and clicked the star and got an empty interface

![screenshot_2015-03-04-10-08-18](https://cloud.githubusercontent.com/assets/516458/6486140/dbc1532e-c256-11e4-9308-698a03afe0b1.png)

Just having a lot of issues with navigation and data loading and whatnot with that favorite screen.

**Comment by ZachOrr** [comment]
2337 also doesn't show up in the "Favorites" area under "myTBA"

**Comment by phil-lopreiato** [comment]
Thanks for the report. Sometimes the mytba cloud operations take a little bit of time (network latency, can't cache, etc.) and it sometimes locks up the db, which is why you saw a blank screen. I'd guess your "add favorite" didn't go through, which is why is didn't show up in the mytba list. You can confirm this on http://www.thebluealliance.com/account/mytba

Can you go back and try and add a favorite? Sadly, the button doesn't show feedback while it's working - it's in the plan to make a spinning progress bar appear while it's working. You might have to wait for the call to finish - the button will turn green on success, and red on error.

**Comment by ZachOrr** [comment]
Yeah, I assume it didn't save because "Back" doesn't save, and the checkmark wasn't responsive.

**Comment by phil-lopreiato** [comment]
Sometimes the button takes >5 seconds to do things. Can you try and add a favorite, and just wait? I'm curious if it's just network latency blocking things up or some other issue.

**Comment by fangeugene** [comment]
We really need to block user interaction when we're making a call to the server.

**Comment by ZachOrr** [comment]
I'm no mobile expert, but I would always update the UI and then let them know a call failed later. So, when I press the star, have it save as a favorite on my phone and update that in the UI and take me back. If the call fails for whatever reason, display a toast or something saying, "Unable to save 2337 as a favorite" or some copy like that, and update it on my phone.

Instagram does that sort of thing when you like photos. It shows you the animation and shows them as liked in your timeline, and then tries to send that up to the server. If it fails in their case it quietly fails and unlikes the photo. I'm not sure if they do any sort of retries or whatnot, so it might be more complex than that. But they update the UI with actions and let the server respond whenever it happens to get around to it.

**Comment by fangeugene** [comment]
I like that. I would have the failure show up as a notification if the app isn't open. If someone hits save and immediately closes the app or turns off the display, and the write fails to go to the server, we want it to be obvious that it failed. Or something along those lines. 

I don't want people saving stuff, not realizing it wasn't saved, and then complaining about not getting notifications

**Comment by phil-lopreiato** [comment]
Yeah, we really do need to block UI interaction, and display a loading indicator.

The error handling is alright at the moment, it looks like this
![screenshot_2015-03-04-10-44-24](https://cloud.githubusercontent.com/assets/2754863/6486933/4a19ba8c-c25c-11e4-91c2-8f6752a174d4.png)

**Comment by phil-lopreiato** [comment]
@ZachOrr got this fixed in the myTBA popup from events/teams view (see afde603). It'll be harder to do the request from the myTBA screen in the background, for reasons I explained in the commit message, so that'll have to come later. 

Open for ideas, though.

**Comment by nwalters512** [comment]
I believe this is no longer an issue. We update the UI immediately when the checkmark is pressed, and show a Snackbar later to confirm a successful save or warn about an error. There's still room for improvement (showing a circular progress bar around the FAB), but the core issue here is resolved.
