### ISSUE TITLE
Notification Time Display Inconsistent

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#345]
Some notifications will display in AM/PM, others in 24H time. All these should be in whatever the devices's format is
![2015-03-06](https://cloud.githubusercontent.com/assets/2754863/6525907/8e013b3e-c3d9-11e4-8f90-58743f3746e5.jpg)

**Comment by fangeugene** [comment]
#suchscreenshot

**Comment by nwalters512** [comment]
Check the code for displaying the match list, that shows the time in the
device's preferred time.
