### ISSUE TITLE
Team list does not refresh

### ISSUE THREAD

**Issue by IAmAGitNewbie** [the-blue-alliance/the-blue-alliance-android#357]
While looking at the Awards for Arizona East on my Galaxy S3 I noticed the Rookie award winner was listed as "Team 5539"  That seemed odd since all the other teams nad their names and numbers listed.  When I taped their number, their event activity loaded.  I then used the View Team option to see their name and other info.  When I backed my way out to the Awards page, the name was displayed.

I thought it was odd so I went to the Teams lists and swiped all the way over to the 5000-5999 section.  As I scrolled down I got to the point where the names ended and only numbers were listed:

![screenshot_04](https://cloud.githubusercontent.com/assets/2994465/6764077/99b88b7a-cf5b-11e4-98c0-5ea3964e41b1.png)

I then picked the first team with no name and it loaded just fine.  When I went back to the team lists that team now has a name:

![screenshot_06](https://cloud.githubusercontent.com/assets/2994465/6764082/bb6029fe-cf5b-11e4-8408-ab318f3e3491.png)

I tried selecting the Refresh option 5 times and it does not load the data for those higher number teams.  The data only loads if I manually select each team.

I tried to reproduce this on my Galaxy Tab 2 12 and it lists all of the teams.  I checked my wifes G3 and the teams display fine. 

Should the Refresh option refresh the team info or do I need to try clearing the cache and maybe the existing data?

Similarly, my Tab 2 lists team 5538 as "Jaguar Robots" but my G3 and the TBA web site list them as "DVHS Cyborgs".  When I open the team on my Tab 2 it will say "DVHS Cyborgs" but when I go back to the view (and Refresh it on the Tab 2), the list view still says "Jaguar Robots".

**Comment by phil-lopreiato** [comment]
The refreshing this is a side effect of a shortcut we take to keep load off the server. The app uses only local data to display those team names, so we don't have to hit >50 endpoints for some events. The problem is that if a team is added after you do an initial download, you won't have the name to display. That's why it show on some devices, but not others (it depends on when the initial download happened).

The second thing is less clear. Maybe the team name was changed in TIMS and it's not propagating properly?

**Comment by IAmAGitNewbie** [comment]
The initial install on my G3 was early to mid January while my Tab 2
install was very recent so that could explain the difference; those higher
rookie teams may not have been available when i initially installed.

I understand the need to minimize the server load and data traffic.
Unfortunately for me this has resulted in incomplete data.  When I check
the Team list for 5000-5999 I find I have a gap in my data.  I see team
5573 followed immediately by 5785 (The Shield).  5785 only appears because
I explicitly opened them from the Rookie All-star award at some regional
while testing my bug report.

The typical expectation for a "refresh" action is that the app will get new
data and update existing data.  If the refresh action from the team view
(not the event teams list) isn't going to make sure I get all the currently
known teams then perhaps it should removed to avoid user confusion.

I will try flushing the app data and reinstalling after this weekend is
over to see if that resolves this issue.

**Comment by phil-lopreiato** [comment]
The team list not refreshing when you hit the button is definitely a bug - all that data should be explicitly fetched when you request it. You can see [here](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/background/PopulateTeamList.java#L51) that it doesn't hit DataManager for a request from the web. 

The more interesting question is what to do with the stale entries every year. I'm thinking we should force a data update every year to get the new events/teams/whatever. 

Thanks for reporting these odd cases, by the way!
