### ISSUE TITLE
Getting notifications for non subscribed activity

### ISSUE THREAD

**Issue by IAmAGitNewbie** [the-blue-alliance/the-blue-alliance-android#374]
I just noticed that I am getting notifications for upcoming matches of my team:

![notification01](https://cloud.githubusercontent.com/assets/2994465/6986472/5b9d6850-d9f2-11e4-8d09-1821b4488809.png)

but I did _not_ subscribe for that kind of notification:

![notification02](https://cloud.githubusercontent.com/assets/2994465/6986478/6e0b0682-d9f2-11e4-93cc-66a527469e42.png)

So why do I get both upcoming match notifications AND score notifications?  

I did remove the app and reinstall it to clean up any issues related to getting data to early in the season.  Could it be that any notifications I set then are in effect even though my client thinks differently?  I saw nothing subscribed when I reran the app after the reinstall so I resubscribed to just match scores.  I wonder if the server has a different view of what I want.

**Comment by nwalters512** [comment]
Can you check in the myTBA view from the nav drawer if you've requested
upcoming match notifications for any of the teams in that notification?

**Comment by IAmAGitNewbie** [comment]
Under myTBA the team settings show everything checked.  Those are likely from my original app install when I was checking out all the cool features.  When I pull up the team from the event I see only the 1 checkbox (above).

Should the myTBA team setting override the team@event settings or be the backup for a team if no event specific settings exist?  I suspect the former but would like confirmation.  

Hmm, the myTBA team@event info is different than the team info when on the event which I filed as a separate issue.  That likely explains the apparent spurious notifications.  I will try changing the myTBA team@event settings and see if that resolves the extra notifications.

**Comment by phil-lopreiato** [comment]
See https://github.com/the-blue-alliance/the-blue-alliance-android/issues/377#issuecomment-89415660

Is this issue still relevant, or has it been superseded by the others?

**Comment by IAmAGitNewbie** [comment]
Yes this was answered in the other thread on settings where you said they are OR'd with the Team and Team@Event settings.  

I had an old Team setting under myTBA that had all the notifications selected.  Not seeing that in the notifications page when I pull it up from the team settings from the event lists was causing confusion.

**Comment by phil-lopreiato** [comment]
Gotcha. I'll close this one, then
