### ISSUE TITLE
remove the "private" option for notifications since they don't have any private data

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#381]
I propose that we remove the `private` option ("When Device is Unlocked") or the entire `secret`/`private`/`visible` Lock Screen Notifications choice because TBA notifications don't contain any private information.

Notifications are a terrific feature. People should not have to find this setting, understand it, and set it to see them.

The `secret` ("Never") vs. `visible` ("Always") choice has low utility -- would anyone who adds subscriptions and enables notifications want to hide them from the lock screen?

At least the default should be visible, not private. (Would just changing the default in notification_preferences_lollipop.xml help users who didn't explicitly pick?)

**Comment by phil-lopreiato** [comment]
Good call, those settings are a bit of a relic from when we were figuring out what all the notification settings did.

You should be able to change the default in [notification_preferences_lollipop](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/res/xml/notification_preferences_lollipop.xml) and the defaults in [this method](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java#L156).

**Comment by nwalters512** [comment]
Looks like this is still an issue. The default preference should definitely be "always", and I still think it's probably a good idea to remove this option entirely.

**Comment by 1fish2** [comment]
+1
