### ISSUE TITLE
the Recent Notifications screen should auto-update when a notification arrives

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#382]
If you're viewing Recent Notifications when a notification arrives, the screen should update. It doesn't.

This is easy to test using the test_notification.pyc script in PR #379

**Comment by phil-lopreiato** [comment]
The notifications should get put on the eventbus, so recent notifications can subscribe and update

**Comment by nwalters512** [comment]
We can probably just post a "NotificationsUpdated" event and have the recents list requery the database then.

**Comment by phil-lopreiato** [comment]
That'll work also.

(and @1fish2, if there are any issues in the [CMP Milestone](https://github.com/the-blue-alliance/the-blue-alliance-android/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22CMP+2015%22) you want to take, just comment saying so and I'll assign it to you)

**Comment by 1fish2** [comment]
Sure. You may assign this one to me. Any tips, let me know. I'll read up on EventBus; other than that it sounds like it'll be straightforward.

What does the [ready](https://github.com/the-blue-alliance/the-blue-alliance-android/labels/ready) label mean?

**Comment by phil-lopreiato** [comment]
Ready just means it doesn't have any dependencies and should be all set to work on. There's a [waffle.io](https://waffle.io/the-blue-alliance/the-blue-alliance-android) readme badge that shows the number of these. 

Actually, I can't assign you an issue if you're not a member of the organization. TIL...

**Comment by phil-lopreiato** [comment]
You can see an example of EventBus in [RefreshableHostActivity](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/43de55341c23ceccc094ff714d8a321ef3736a89/android/src/main/java/com/thebluealliance/androidclient/activities/RefreshableHostActivity.java#L241). Make sure you subscribe and unsubscribe (which you'll see in onResume and onPause)

**Comment by 1fish2** [comment]
The event code works but it has a side effect: If the Recent Notifications fragment is visible when a new notification arrives, it won't get merged into a summary notification. (If there was a summary notification visible, the new one won't get added to that. If there was a non-summary notification, the new one adds another system notification.)

My first hypothesis was the `getNotificationId()` implementations using the current time to construct non-stable IDs caused this, but constructing notifications with an ID a sequence counter didn't fix it.

Looking closer at `SummaryNotification.isNotificationActive()`, it gets the notifications to merge from a DB table, and that has to have > 1 entry to decide to merge.

Does refreshing the Recent Notifications fragment clear the list of notifications to summarize? `table.dismissAll()`.

**Comment by nwalters512** [comment]
If the recents screen is visible, a system notification shouldn't be
visible and shouldn't be created when a new notification comes in. At
least, that's what I would expect the behavior to be.

**Comment by 1fish2** [comment]
That would be reasonable as long as a push notification still plays the notification sound & vibration (per settings) and updates Android Wear, also going to the Recent Notifications fragment should clear the app's system notifications.

Can the system notification mechanism handle sound, vibration, and Wear extensions without displaying anything in the notification area? If so, and given a way (a static boolean?) for the GCM Intent receiver to tell that the Recent Notifications fragment is visible, this approach is straightforward.

Alternatively, intents from a system notification to the app would be the way to clear the push notification from the summary list.
