### ISSUE TITLE
Notifications Not Being Marked As Read

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#384]
Test case:

1. Receive a push notification. (`test_notification.py` in #379 makes this easy.)
1. Tap the resulting system notification to open a TBA activity. (To reproduce this bug, do not swipe away the notification or clear all notifications.)
1. Receive another push notification.
1. Result: A group summary notification that lists the new notification and the previously dismissed notification.
1. Tap the summary notification.
1. Result: That goes to the Recent Notifications activity, which currently clears the list of "active" notifications. So the next incoming notification will properly display all by itself.

This seems to be caused by [Android Issue 41253: The deleteIntent of the Notification doesn't get called when the user touches the Notification](https://code.google.com/p/android/issues/detail?id=41253). The app creates notifications with `setAutoCancel(true)`, which is supposed to make tapping the notification send its delete Intent (dismiss notifications) as well as its content Intent (open an Activity). But Android doesn't send the delete Intent in this case.

Since the fix for #382 exacerbates this bug, I'll fix this in the same PR.

**Comment by phil-lopreiato** [comment]
Awesome! Try and tag your commit messages with the issue number where you can, just so they get linked to the right place.
