### ISSUE TITLE
Possible Incorrect team@event Summary Alliance Determination 

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#387]
From comments on 9d7256f3ffb0c53174aebe38074e9acf8a3c19a (https://github.com/the-blue-alliance/the-blue-alliance-android/commit/9d7256f3ffb0c53174aebe38074e9acf8a3c19af#commitcomment-10676779)

**Comment by 1fish2** [comment]
Is the task here just to fix the contains() test (vs. more support for 1/8 finals)? If so, you may assign it to me.

**Comment by phil-lopreiato** [comment]
Both need to be done, but we can split off more support for 8th finals and do that another time
