### ISSUE TITLE
Remove Events From DB After They're Removed From API

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#389]
TBA Android shows "Carter Division" as an extra, 9th (sub)division of the Championship Event.

Carter is not in http://www.thebluealliance.com/events or http://www.usfirst.org/roboticsprograms/frc/blog-New-Subdivision-Names

**Comment by phil-lopreiato** [comment]
It's a relic of an older issue on the server, where we had incorrectly entered one of the names. 

We need to make the event model do something similar to what we did here https://github.com/the-blue-alliance/the-blue-alliance-android/commit/022a92ea94b6570c4a709a06c0816a6bb090490c ([specifically](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/models/Match.java#L479))
