### ISSUE TITLE
Notification Testing Script Temporarily Disabled

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#392]
Had to remove the dynamic permission from the manifest to get the Play Store to accept the build.

@1fish2 is there any other way to accomplish that?

See details in d6abe304a55462f7e1a8ef3cbb90f9fca46d428f

**Comment by 1fish2** [comment]
Sigh. It was a good trick. I'll explore further.

**Comment by phil-lopreiato** [comment]
Yeah, it was sad when the Play Store console yelled at me about it. :(

Back to the drawing board...

**Comment by 1fish2** [comment]
[Manifest merger](http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger#TOC-Placeholder-support) looks viable. I'll try that.

It's also possible for gradle code to modify the manifest while copying it from one directory to another, but from various SO questions, the specifics seem to change frequently.

Another idea is for the debug app at runtime to try to turn off that permission filter or register a broadcast listener with no filter, although at best that'll only work while the app is running.

**Comment by phil-lopreiato** [comment]
Closed by #393
