### ISSUE TITLE
2015 Events Appear Double In Search

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#397]
![screenshot_2015-04-17-15-18-20](https://cloud.githubusercontent.com/assets/2754863/7209284/381fea50-e515-11e4-8488-969594362dab.png)

**Comment by phil-lopreiato** [comment]
Items aren't duplicated in serach_events
![screenshot from 2015-04-17 15 17 27](https://cloud.githubusercontent.com/assets/2754863/7209291/51e0ca9a-e515-11e4-813f-1de20b1bb9fe.png)

**Comment by fangeugene** [comment]
Ruh roh not good.

**Comment by phil-lopreiato** [comment]
It's the search events table, so it's not that bad. I've also figured out  fts3 tables don't support FOREIGN KEY constants, which is also a bigger problem.
