### ISSUE TITLE
Recent Notifications Render Like Gameday Items

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#402]
Because it's prettier that way

**Comment by phil-lopreiato** [comment]
This is going to require changing what data is stored, so it will only work for notifications received in the future. Should still be doable, though

**Comment by phil-lopreiato** [comment]
This is out of scope for this weekend. Will be used in a future release

**Comment by nwalters512** [comment]
Gameday elements and recent notifications are now rendered the same way.

**Comment by phil-lopreiato** [comment]
Are they? I don't remember doing this...

**Comment by nwalters512** [comment]
Woops, I read the source code wrong. Scratch that.

**Comment by nwalters512** [comment]
Guess I was too excited to clean out old issues :)
