### ISSUE TITLE
Webcast List Handle iframe casts

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#403]
Since CMP Webcasts will be iframe embeds, we should make sure that non-deep linkable webcats are handled properly.

I think we should modify [WebcastHelper](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/helpers/WebcastHelper.java) to make all other webcasts type WEB_GAMEDAY, have them say "watch on the web", and link to http://www.thebluealliance.com/gameday#layout=0&view_0=eventKey

**Comment by 1fish2** [comment]
Would it work to use a WebView to display iframe-embedded video?

**Comment by phil-lopreiato** [comment]
[It seems like that's possible also](http://stackoverflow.com/questions/5167907/is-it-possible-to-use-iframe-in-uiwebview)

So I guess we could do iframes that way. @fangeugene what exact types are the CMP webcasts going to be?

**Comment by fangeugene** [comment]
http://science.ksc.nasa.gov/robotics/first/st-louis-2015/

Last year I couldn't figure out any way to put them into gameday other than iframing them. (AKA it didnt follow our standard MMS or RTMP patterns)

**Comment by phil-lopreiato** [comment]
Wait, there are going to be flash streams, aren't they? Can't display those on mobile, so I guess kicking the user out to GameDay is the only thing we can do

**Comment by fangeugene** [comment]
Seems like it. Or just don't ship Webcasts for Champs if it's not going to work anyways.

**Comment by phil-lopreiato** [comment]
I'll have them display "Watch on GameDay" and open the web GameDay in the browser. That's easier than removing it, and it'll let users with flash (for some reason) still watch them.

**Comment by synth3tk** [comment]
They're using a m3u8 playlist, which means most likely [HLS](http://www.jwplayer.com/html5/hls/). This pleases the Android gods greatly. I'm not sure if the Gameday player can handle HLS yet, but I'll give it a go tonight or tomorrow.

I'm not familiar with Android development, but if we get the playlist URL for every field, you should be able to play it natively in the Android player, right?

![nasam3u8](https://cloud.githubusercontent.com/assets/2099988/7244097/435396a6-e7a4-11e4-9a2f-78552b6cdf5b.png)

**Comment by phil-lopreiato** [comment]
Ooh, that's pretty nice. I _think_ the default player can handle it fine, but I'd like to test it somehow.

We should (and @fangeugene) decide how that data will be encoded internally (make a new type, or just kept in an iframe), which will decide how it appears in the API, which drives how we display it on the app end.

**Comment by fangeugene** [comment]
If either of you can figure out how to do a new type, I'm down for it. Otherwise, I'll just create a few temporary pages and iframe those.

**Comment by phil-lopreiato** [comment]
@synth3tk if you can get GameDay to display m3u8 playlists, can you make it a new internal type, with `channel` being set as the playlist file? That way we can nicely display html5 video :)

**Comment by synth3tk** [comment]
I can definitely do that! Let me finish getting setup and I'll put something together.

For your tests, what better than a feed from NASA? Just clicking that link gives you the option to play it in a player, so I'm pretty sure we should be good to go, support-wise.
http://www.nasa.gov/multimedia/nasatv/NTV-Public-IPS.m3u8

**Comment by phil-lopreiato** [comment]
Cool! I'll play around with that. The only think I'll need from you is the format of the json dict you end up storing for the webcast. I propose something like:
```
{
 "type": "html5" (should just be able to render with `<video>` tag)
  "channe":  "http://www.nasa.gov/multimedia/nasatv/NTV-Public-IPS.m3u8" (or whatever)
}
```

**Comment by phil-lopreiato** [comment]
That was actually really easy. I implemented it in the app according to what I said above. If you change it, just post and I'll update.

![](https://dl.pushbulletusercontent.com/9eGVB9yx2Wl5iechvWm9e9pLRrEewgHj/Screenshot_2015-04-20-23-10-59.png)

**Comment by synth3tk** [comment]
It'll probably just stick to that format above. Makes the most sense.

**Comment by phil-lopreiato** [comment]
:+1:

**Comment by 1fish2** [comment]
Awesome!

**Comment by synth3tk** [comment]
Running into issues integrating this desktop-side and I still haven't started packing. Thinking of adding an `iframe` item and just using that for the gameday site, leaving `channel` for the m3u8. That shouldn't break anything with your implementation, correct?

**Comment by phil-lopreiato** [comment]
I can make a case to handle that. 

Or if you want, I might have a little more time to debug what you've got since I don't have to pack and catch a flight to STL :(

Up to you

**Comment by synth3tk** [comment]
I don't have to hit the road for another few hours, so I'll see what I can accomplish before then.

**Comment by synth3tk** [comment]
Got it! No changes need to be made to the formatting. About to commit in a few minutes.
