### ISSUE TITLE
Gameday live ticker causing crash

### ISSUE THREAD

**Issue by jlmcmchl** [the-blue-alliance/the-blue-alliance-android#404]
Device: Oneplus One

On selecting the Gameday tab, the Live Ticker will try to load, and crash. So, I cannot go to the live streams section to watch a stream, once those have been made live.

**Comment by fangeugene** [comment]
This is a known issue with v2.2.0. V2.2.1 is rolling out.

**Comment by phil-lopreiato** [comment]
Sorry about that. It was in issue from when we imported the preliminary schedules (without match times), so the app was expecting some data that wasn't there. The issue has been fixed for v2.2.1, in a206b3db454914625a84ca9dfa1e617a3f185c95 and 84b881f8081e1f5f3cd3b5fb657c26f42dd60514

**Comment by jlmcmchl** [comment]
No worries. Glad you guys were already made aware of the issue, and have corrected it. Thanks!

**Comment by phil-lopreiato** [comment]
FYI: If the update hasn't hit your device yet and you don't want to wait, you can [download the apk](https://github.com/the-blue-alliance/the-blue-alliance-android/releases/tag/v2.2.1) and install it yourself.
