### ISSUE TITLE
Chromecast support for streaming webcasts to your TV

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#405]
[This is such a good feature request it's worth splitting it out from #94 ]

**Comment by phil-lopreiato** [comment]
For webcasts hosted by a streaming site, we're at the mercy of their mobile apps. Only [twitch](http://blog.twitch.tv/2014/09/twitch-on-chromecast-is-finally-here/) and YouTube support it.

We can probably implement chromecast for the new html5 video type. I don't think we can do it for any other, though.

**Comment by phil-lopreiato** [comment]
By now, most streaming apps implement Chromecast support on their own, so I don't think there's much we need to do within TBA
