### ISSUE TITLE
match schedule view doesn't mention the day

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#406]
In a CMP match schedule like this:
![match-schedule](https://cloud.githubusercontent.com/assets/1043120/7292301/a1d600e0-e94f-11e4-9a9d-4205105acd3c.png)
you have to look closely to notice that the match times jump backwards, no doubt across a day boundary.

It'd be nice to put a visual indicator (bold line or color change or something) at the day boundary (an overnight gap in the match schedule) and also show the day of week next to the match time (in the viewer's potentially distant time zone) whenever it differs from the preceding entry.

**Comment by nwalters512** [comment]
Good call. I'm not sure if we were planning on a maintenance release today,
but this would be worth adding.

**Comment by 1fish2** [comment]
I'll try to fix it this afternoon (Pacific), in between watching 8 match streams and other things on the schedule. Review it carefully when deciding if today is a good day to release.

**Comment by phil-lopreiato** [comment]
I see two crashes in the console that are probably worth fixing tonight, so we can do a minor release. 

Just make sure to be extra careful about matches not having UTC time data, time string data, both, or neither. Graceful failures are nice :)

**Comment by 1fish2** [comment]
Can anyone else build the current 2015-comp-freeze code?

Android Studio 1.1.0 has 16 build errors in MatchTest.java trying to access static Match methods:

> C:\sourcecontrolled\the-blue-alliance-android\android\src\test\java\com\thebluealliance\androidclient\test\models\MatchTest.java:47: error: cannot find symbol
        JsonObject redAlliance = Match.getRedAlliance(alliances);
                                      ^
  symbol:   method getRedAlliance(JsonObject)
  location: class Match
...

But the IDE's control-click-through works fine on these symbols. Also, EventHelperTest builds OK. These unit test build errors keep the app from running on a device.

AS also doesn't like this line in android/build.gradle
> compile 'com.google.http-client:google-http-client-gson:1.19.0' exclude module: 'httpclient'

complaining `Cannot resolve symbol 'compile'`

The current AS version, 1.2 RC2, doesn't fare any better.

**Comment by 1fish2** [comment]
Fixed now, after reboot, `gradlew clean`, other incantations.

**Comment by phil-lopreiato** [comment]
Whoops, sorry I missed that. Glad you got it worked out!
