### ISSUE TITLE
Summary notification shows "@17041057" after #7

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#412]
When a summary notification exceeds 7 entries, it shows `@17041057` for the rest.

I verified that the app is passing the right data to `NotificationCompatBuilder`, and indeed a web search shows that [it's an Android 5.1 bug](https://code.google.com/p/android/issues/detail?id=168890).

![18-notifications- 17041057](https://cloud.githubusercontent.com/assets/1043120/7314327/56701e8c-ea18-11e4-96c6-b7aeee087745.png)

The bug does not appear to be in `NotificationCompatJellybean` so I think the choices are

1. Live with it and hope Google fixes it.
1. Rather than adding 8+ items to a summary notification on Android 5.1, add 6 items plus a "more..." line. That seems reasonable, although not a big deal.

**Comment by phil-lopreiato** [comment]
Yay for silly android bugs!

I like the second option, maybe we do it for all devices so a lot of notifications don't take up the whole shade

**Comment by 1fish2** [comment]
Good idea. I'll do that. It's simpler and avoids the problem of switching it off in Android 5.2 or whatever. No rush to deploy the fix.
