### ISSUE TITLE
team's "next match time" is wrong after a data gap

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#413]
The next match time for team 1678:
![1678-next-match-wrong-time](https://cloud.githubusercontent.com/assets/1043120/7324934/86c0c12a-ea6f-11e4-83f7-09f7416b2964.png)
is 4 hours ago.

It's easy to see what happened since the team's match schedule has gaps in posted match results:
![1678-match-times](https://cloud.githubusercontent.com/assets/1043120/7324952/b1bcb10e-ea6f-11e4-98d7-57007616c98a.png)

Strangely, the same problem does not happen for the field's match schedule:
![newton-next-match-right-time](https://cloud.githubusercontent.com/assets/1043120/7324977/dc67b89a-ea6f-11e4-9c28-de3eebbf2542.png)

even though the field has two gaps in its posted match results (I could only fit one into a screen shot):
![newton-match-times](https://cloud.githubusercontent.com/assets/1043120/7324988/fa5f7482-ea6f-11e4-8be4-c6b00783f094.png)

[I'll look at the code.]

**Comment by phil-lopreiato** [comment]
This is an interesting one - we're building resiliency! 

The solution might be to iterate backwards instead of forwards over the match list to find these

**Comment by 1fish2** [comment]
Yes. `MatchHelper#getNextMatchPlayed() and `getLastMatchPlayed()` should either iterate backwards or else loop all the way through the list. They're called together so maybe combine them into a one-pass method that returns the pair.

`PopulateEventMatches#doInBackground()` separately searches via a one-pass loop. It doesn't break out early so a gap will fool it only if the final match was played.

We should make `PopulateEventMatches` call the same utility method(s) and add unit test coverage for these cases.

**Comment by phil-lopreiato** [comment]
Agree on all those points.
