### ISSUE TITLE
Add info snackbar when refreshing

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#417]
It's an unpleasant experience to sit there during a refresh and have no idea what's going on. Refreshable activities should have a "Refreshing {info/matches/awards/etc}" when a refresh is in progress.

**Comment by Adam8234** [comment]
You're not the only one that thought that. One of my friends in the stands
was confused on what was updating within each of the refreshable hosts. So
yeah, something subtle would be a nice addition. :)

**Comment by phil-lopreiato** [comment]
I don't think this is an issue anymore with the new datafeed.

No data views + much faster loading means there are many fewer blank screens
