### ISSUE TITLE
Admin Push Message to Users

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#418]
[Inspired by Spyder](https://twitter.com/FRCZach/status/592325130006704128) and as an extension of admin broadcasts, we should provide a way to have a persistent message appear for uses.

We can make an unauthenticated endpoint to [cloud endpoints](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/mobile_main.py) and have the app hit it on startup. Messages could have 'title, 'content', 'expiration time' properties.

If there's a message, we could display it as a persistent [warning message](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/activities/BaseActivity.java#L103) until it's canceled or expired.

**Comment by phil-lopreiato** [comment]
From #501 
> Admin messages are best discussed elsewhere, but I think those should be implemented as modal dialogs. Snackbars are easily missed; a modal forces the user to acknowledge that there's a problem and read the message about it.

If we show these as dialogs, how often and where do we show them without being really irritating, etc...

**Comment by nwalters512** [comment]
(Not to be copying Spyder but) Spyder uses dialogs, and it works well for them. I would say show it once when the app first becomes aware that there's an issue.

My main motivation for doing this is the fact that by default, only one snackbar can be shown at a time. If we want to show multiple snackbars simultaneously (for instance, showing a persistent "FIRST screwed up" message and a temporary "myTBA save succeeded" one), we'd have to roll our own snackbar and corresponding behaviors, which I'd like to avoid if possible.

**Comment by phil-lopreiato** [comment]
> (Not to be copying Spyder but) Spyder uses dialogs, and it works well for them. I would say show it once when the app first becomes aware that there's an issue.

This is definitely the easiest solution, but users could forget at stuff. I guess once at start is a good compromise? 
...
In order to keep pace with https://github.com/the-blue-alliance/the-blue-alliance/issues/1303....

 - [ ] Add new data (for message) into ApiStatus class
 - [ ] Remove Admin push broadcast notification type
 - [ ] Add send-to-sync notification that refreshes API Status in background
 - [ ] Add info notification that notifies an event (or entire datafeed, if simple to do on server) is down

**Comment by nwalters512** [comment]
I guess one option is to move admin message showing stuff to BaseActivity, and modify the view hierarchy to insert a persistent message at the bottom of the screen? Messy-ish, but we could make the styling match/resemble a snackbar. I'll investigate in a few days.
