### ISSUE TITLE
Use Material Dialogs library

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#419]
Might as well take this easy step to achieving #materialyolo everywhere: https://github.com/afollestad/material-dialogs

**Comment by tanis7x** [comment]
Google actually [just released version 22.1 of the support library](http://android-developers.blogspot.com/2015/04/android-support-library-221.html), which includes Material dialogs via [`AppCompatDialog`](http://developer.android.com/reference/android/support/v7/app/AppCompatDialog.html) and [`support.v7.app.AlertDialog`](http://developer.android.com/reference/android/support/v7/app/AlertDialog.html)

**Comment by phil-lopreiato** [comment]
Which will be available in #371!

**Comment by nwalters512** [comment]
Looks like we did this at some point in the last few months!
