### ISSUE TITLE
Team view shows "No events found" while events are loading

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#423]
Steps to reproduce:

1) Open a team details view for a team you haven't viewed before
2) Switch quickly to the "events" tab
3) While the events are loading, the list displays "no events found"; the list populates once the events are loaded.

Not totally sure how to fix this one. Our data stack is so deep that it's going to be fun to track down why this happens :) will investigate.

**Comment by phil-lopreiato** [comment]
This sounds like the database lock thing :/

**Comment by nwalters512** [comment]
The reason I think it isn't is because a task would have had to have completed in order for the message to be displayed; otherwise the loading indicator would be displayed if the database was locked up and couldn't complete.

**Comment by phil-lopreiato** [comment]
The semaphore acquire probably timed out and it got NO_DATA back

**Comment by nwalters512** [comment]
But timed out immediately? That doesn't seem right.
