### ISSUE TITLE
Remove tabs from "Team" view

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#424]
I don't think the tabs really do a whole lot; if a user is looking for a specific team, they'll probably just search for it instead of swiping through some tabs and then scrolling through a list of 1000 teams. The tabs don't really do any harm by being there, but they don't really do much for the user, either. Commence debate.

**Comment by 1fish2** [comment]
The tabs aren't a great way to get to one of 6000 teams but it's better than a huge scrolling list, and search is only good when you're looking for a specific team number that you know, ± query substring matches. This could use a more clever solution, but I don't have one to suggest.

BTW the pressure on this would be reduced if it was very fast to use myTBA as a list of bookmarks, that is, without waiting on network I/O.

**Comment by phil-lopreiato** [comment]
> but it's better than a huge scrolling list

and

> search is only good when you're looking for a specific team number that you know, ± query substring 

are the main reasons I'm in favor of keeping the tabs. Plus, it keeps parity with http://www.thebluealliance.com/teams

> if it was very fast to use myTBA as a list of bookmarks, that is, without waiting on network I/O
When we do the data model rewrite, this is in the plan. I think we can combine GCM + account sync service to keep these up-to-date so they always insta-load

**Comment by 1fish2** [comment]
Yay for that data model rewrite (whether it uses account sync, or Firebase, or low tech background polling).

**Comment by nwalters512** [comment]
I guess keeping tabs makes sense!
