### ISSUE TITLE
Follow "empty states" guidelines

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#426]
Moar guidelines! Adding "no items" messages like these would make the app a little more friendly. Something like a simple grey icon and short, to-the-point text centered on every empty page would look better than the "No <thing> found for this <thing>." messages we currently have.

**Comment by phil-lopreiato** [comment]
Absolutely. I think [DataBinding's ViewStub](https://developer.android.com/tools/data-binding/guide.html#viewstubs) can help us

**Comment by Adam8234** [comment]
Could we use [setEmptyView](http://developer.android.com/reference/android/widget/AdapterView.html#setEmptyView(android.view.View)) in the ListView View?

**Comment by nwalters512** [comment]
'setEmptyView' works just fine, it only saves us a few lines of code though. I'm less concerned about the specifics of implementation, seeing as we already have views that will show and hide depending on if we have data.
