### ISSUE TITLE
[App v3] Move Network Requests to Retrofit

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#427]
Add [Retrofit](https://github.com/square/retrofit) library and define an API interface with a single endpoint (use hose tba.com/api/v2) with the endpoint as a single paramter.

This way, we can use Retrofit's capability to return an Observable with the network result. We need to migrate our network stack to work with Observables and have something consume them.

We will need to refactor RefreshableHost a bit. I'm thinking it consumes all incoming network Observables for the Activity. The child Fragments can report which endpoints they require (some `public static final` variable, maybe) and be notified when each endpoint comes in, and when all requests are loaded. The RefreshableHost will hold all the content, which the children can query and process. This allows us to eliminate all the `Populate*` tasks

**Comment by nwalters512** [comment]
I'm not sure if this is the right way to go about things. If we're going to rely directly on Retrofit's Observables, it seems like we'd have to eliminate our entire caching and data layer and deal directly with the results from Retrofit. And if we're using a single endpoint with the path as a parameter, we can't take advantage of the one thing that really makes Retrofit worthwhile: its ability to automatically convert incoming data into a Java object.

**Comment by phil-lopreiato** [comment]
Well, we could do the [full API spec](https://github.com/phil-lopreiato/tba-apiv2-java/blob/master/apiv2/src/main/java/com/plnyyanks/tba/apiv2/interfaces/ObservableAPIv2.java), but it might be a little more complex.

I don't think this would require eliminating the caching layer - we'll just have to modify the caching to 1) always return Observable<Something> and just hit retrofit instead of the current HTTP stack. I don't think it's impossible, although it may take a little bit of trial and error

**Comment by nwalters512** [comment]
I guess my question is, what does Retrofit provide that we need?

**Comment by phil-lopreiato** [comment]
I like the Auto-deserialization (if we want to go with it), and I really like the simplicity of building up the API. Plus, the Observable support.

Of course, we could just [make our own](https://gist.github.com/alexwen/4b337bc669509a696b5b) Observables with okHTTP

**Comment by nwalters512** [comment]
If we want to continue to use our own caching, we'll have no choice but to build our own observables at least half the time, and I think it's best that we always build our own for consistency's sake.
