### ISSUE TITLE
Investigate Automated (ish?) Releases

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#438]
My laptop with the Play Store keys shouldn't be a single point of failure in the release cycle.

I'd love to automate the process with a Push-to-deploy branch that can do the whole cycle from Travis CI. The process might look something like this:
 - Have a script in the repo to prepare a release. [Bump](https://github.com/palantir/gradle-gitsemver) [version](http://www.jayway.com/2015/03/11/automatic-versioncode-generation-in-android-gradle/), prompt for a changelog (define some format, and put a black file up to `EDITOR`), and add appropriate git tag. Then, if all good, push to a branch specifying the appropriate release channel
 - If a CI build is run on a release branch and everything passes, use [Gradle Play Publisher](https://github.com/Triple-T/gradle-play-publisher) to push a build from CI (needs service account keys stored in CI vars)

Issues
 - Where do you get Play Store release keys? I think there's a way to get it securely from Google Cloud Storage using the same account service keys.
 - Permissions. Anyone with push access to the repo gets to deploy? Maybe we require gpg signed commits and whitelist keys on CI side?

**Comment by 1fish2** [comment]
> My laptop with the Play Store keys shouldn't be a single point of failure in the release cycle.

Indeed. To fix that part, you could store the keys in a password vault with cloud backup. LastPass can securely share an entry with select people.
