### ISSUE TITLE
Make "Recent Notifications" list update when a new notification comes in

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#441]
It's a minor detail, but one that we should get around to eventually. When a notification is received from GCM and processed, we should broadcast/event-bus that information so we can automagically update the recent notification list if it happens to be open at the time.

**Comment by 1fish2** [comment]
What remains to do on this given #382 and #384 were implemented?

**Comment by nwalters512** [comment]
I recently rewrote the recent notification stuff to go with the observer pattern that the new datafeed uses, but (afaik) there's no built in refresh/reload mechanism yet. Once that's added, it's just a matter of wiring it up to the Event Bus.
