### ISSUE TITLE
Week Listing for 2016 Events

### ISSUE THREAD

**Issue by bmaher0** [the-blue-alliance/the-blue-alliance-android#462]
On the app, under 2016 events, the Palmetto Regional is listed under Week 1 rather than Week 0.5, offsetting the rest of the weeks by 1.

**Comment by phil-lopreiato** [comment]
It's been special cased in 4ea7e6eb1a1a38ab25fc9f7f661ae0bebd962869 on the rewrite branch, that commit just needs to be picked over to master

**Comment by phil-lopreiato** [comment]
Finally pushed a beta. Prod will get updated soon™
