### ISSUE TITLE
Refreshing Events error on appv3-datafeed branch

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#467]
When refreshing the event list, the active tab shows "No events found." Sometimes swiping to another tab and swiping back fixes it. Other times multiple tabs will show "No events found." Restarting activity fixes it.

Edit: Maybe related. Switching from any year to 2016 results in the first tab (Week 0.5) to have no events found. Switching tabs and switching back fixes it.

**Comment by phil-lopreiato** [comment]
@nwalters512 what do you think the cause for this one was?

**Comment by nwalters512** [comment]
I haven't looked in-depth at how refreshing is handled yet to give an informed response. I've noticed this periodically too though, I've been meaning to check it out. I'll give it a look in my free time.

**Comment by phil-lopreiato** [comment]
I remember it was happening before I implemented refreshing also, and it could be consistently triggered by changing years. 

I'd guess that it has something to do with the first tab isn't explicitly "selected" when the year changes so the binding never gets triggered
