### ISSUE TITLE
GameDay causes skipped frames on branch appv3-datafeed

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#478]
GameDay is very laggy and drops frames.

Also, for example if you switch between GameDay and Events back and forth a bunch of times, then swiping through tabs in Events will start lagging and dropping frames too.

Killing the app and restarting it fixes the issue.

**Comment by nwalters512** [comment]
Can sort of reproduce on my N5, although Gameday has always been sort of iffy given the complexity of the list items. Is this definitely a regression from prod?

**Comment by fangeugene** [comment]
It feels like a regression from prod. My biggest concern is that even if you leave the GameDay activity, it still lags. I don't think prod exhibits that behavior.

**Comment by phil-lopreiato** [comment]
Still CNR. If you see this on the Google Play beta, reopen
