### ISSUE TITLE
Sort myTBA elements

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#480]
Also, use the Team list item used everywhere else if possible.

**Comment by phil-lopreiato** [comment]
I don't think we should change the list elements. I don't like the look when all the different categories look differently. Plus, if we use the same list element everywhere, it gets crazy to add in the model settings item everywhere (which we might want to do eventually, but not now)

![teamlist](https://cloud.githubusercontent.com/assets/2754863/10463168/dd40e98a-71b0-11e5-896d-a7ee43a15a9d.png)
