### ISSUE TITLE
Update Info/Warning Messages

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#501]
Current solution (just a view) doesn't play nice with FAB. We should update to a Snackbar, which should be able to handle all that. We should also abstract out the [info message](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/activities/ViewEventActivity.java#L206) stuff from ViewEventActivity so that we can also show Admin Messages (see https://github.com/the-blue-alliance/the-blue-alliance/issues/1303) without the warning decorations.

![screenshot_20151208-233112](https://cloud.githubusercontent.com/assets/2754863/11676859/3367df5a-9e05-11e5-9a0b-7eb0d5254b57.png)

**Comment by nwalters512** [comment]
Admin messages are best discussed elsewhere, but I think those should be implemented as modal dialogs. Snackbars are easily missed; a modal forces the user to acknowledge that there's a problem and read the message about it.

**Comment by phil-lopreiato** [comment]
Closed by #513
