### ISSUE TITLE
Refactor NavigationDrawerActivity view to include a CoordinatorLayout

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#502]
There needs to be a ```CoordinatorLayout``` somewhere in the view hierarchy for Snackbars to work, so we might as well put one in the view hierarchy that is ultimately used by the rest of the application. This should be a prerequisite for an ideal implementation of #501, where we can move ```showInfo()```/```showWarning()``` to NavigationDrawerActivity and have them be accessible from everywhere and consistent.

(Side note: it's always bothered me how BaseActivity extends from NavigationDrawerActivity; shouldn't Base be the thing from which everything else is extended? Maybe that's just me. But as well as we're messing around this deep in code that hasn't been touched in months/years, we might as well look at this.)

**Comment by phil-lopreiato** [comment]
> Side note: it's always bothered me how BaseActivity extends from NavigationDrawerActivity; shouldn't Base be the thing from which everything else is extended?

BaseActivity predates NavigationDrawerActivity, I think, so it might have been easier at the time to just add the drawer stuff as a superclass?

And there might be cases where we want a nav drawer, but not datafeed bindings (which is what BaseActivity was originally for, but probably isn't the case anymore), but I don't remember for sure

**Comment by nwalters512** [comment]
Doesn't really matter in the grand scheme of things; doesn't affect functionality. I was just reminded of this when I was poking around in that code.

**Comment by phil-lopreiato** [comment]
Closed by #513
