### ISSUE TITLE
Crashes when event/team list is manually refreshed while in airplane mode

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#510]
Steps to reproduce:
1) Force stop application
2) Put device in airplane mode
3) Start application
4) Click the refresh button on the top level teams or events lists
5) Observe weird crash

I'm seeing this behavior on the latest beta from the Play Store.

It looks like the reactive internals are either causing this problem or eating the error.

```
12-17 17:49:20.270 29448-29490/? E/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-2
                                                   Process: com.thebluealliance.androidclient, PID: 29448
```

**Comment by phil-lopreiato** [comment]
This is actually in latest beta (which you're a member of). Prod is still on v2.X which doesn't have anything Rx. Can you repro this on master?

**Comment by nwalters512** [comment]
Right, I meant beta. I'm not seeing this on master.

**Comment by phil-lopreiato** [comment]
Okay, I think we can call this one fixed then. I don't remember exactly which commit it was
