### ISSUE TITLE
Fix Wording in myTBA Skip Confirmation

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#512]
Running the current code in master, 4a3eac2:

Once it fetches the initial data and the user continues past the startup screen, it opens a modal dialog:

    Are you sure you don't want to enable myTBA?
    
    You can always enable it later in Settings.
    
                                  CANCEL   YES

Wait, what? Does CANCEL mean "No, I don't want to enable myTBA", or "I'm not sure I don't want to enable myTBA", or "Don't do anything"? What does YES mean?

Suggestion:

    Do you want to enable myTBA?
    
    You can always enable it later in Settings.
    
                            NOW   MAYBE LATER

https://twitter.com/howardtayler/status/544526400674205698

**Comment by 1fish2** [comment]
(I changed YES to NOW in the suggestion because YES means one thing in response to the question and another thing in response to the "You can always enable it later" tip.)

**Comment by nwalters512** [comment]
Good catch, I should've put more thought into that.
