### ISSUE TITLE
Blue bar for no data/FIRST down showing up where it shouldn't

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#523]
Including but not limited to:

![2015-12-25 02 58 21](https://cloud.githubusercontent.com/assets/1421884/11999421/457dc910-aa72-11e5-838a-115a91ace58b.png)
![2015-12-25 02 57 32](https://cloud.githubusercontent.com/assets/1421884/11999425/5266546c-aa72-11e5-8a6a-4b4bd6977ca8.png)

**Comment by nwalters512** [comment]
Oooops... I thought that was defaulted to be hidden. Will investigate.
