### ISSUE TITLE
Installation failure, error -505

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#532]
From a (1 star) Play Store review:

```
 Getting error code (-505) Google's troubleshooting steps all failed. Uninstalled the app to reinstall and now I still can't install it and I don't have the old version either. Unrooted SGS 4
```

This doesn't appear to be an issue on our side, it's most likely an issue with 5.0 itself: http://android.stackexchange.com/questions/88214/how-do-i-deal-with-unknown-installation-error-code-505

We're going to try to get the reviewer to communicate with us via this issue so we can try to do further troubleshooting.

**Comment by jwgardner** [comment]
I am getting this error as well, can't update from the play store.  Marshmallow 6.0, Moto X Pure.

I was getting -505 error on updating, uninstalled and tried to install, fails.  Cleared cache, data on play store/services.

Let me know if you want any more detail.

**Comment by phil-lopreiato** [comment]
Maybe we should try the steps here: https://www.reddit.com/r/androiddev/comments/40ud0b/users_getting_error_505_when_downloading_our_app/

Seems like Google Play Services broke it without telling us...
