### ISSUE TITLE
Bug: lists scroll to top when resuming activity

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#544]
Steps to reproduce:

1) open an event
2) scroll to "Rankings" tab
3) scroll to bottom of list
4) click on last team
5) once the activity loads, click "Back" (not up, that triggers a different issue)
6) observe how after a second, the list jumps back to the top

This actually applies to all tabs in the activity: if you swipe between several tabs, scroll them all down, then do the above process, they will all be scrolled to the top. There's no reason scroll position shouldn't be persisted.

This appears in several places throughout the app, not only in the "Events" activity.

**Comment by phil-lopreiato** [comment]
Fragment lifecycles are such a pain...
