### ISSUE TITLE
Most EventTeams not being cached locally

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#548]
While investigating #545, I discovered that most (but not all) EventTeams aren't being cached in the database. Specifically, most of the time EventTeamsTable.getEvents(...) will return nothing due to an empty cursor, even after the cache definitely should have been populated with the appropriate things. There are some exceptions: on my device, Palmetto 2015 and 2016 are consistently cached, as are some other events (check out the database in Stetho to see exactly what's there). This doesn't really impact user experience, as the network requests will take care of populating things pretty quickly, but this should really be fixed for correctness' sake.

**Comment by phil-lopreiato** [comment]
I checked it out on stetho with current master and it seemed like they were getting added properly. Can you confirm this wasn't fixed by #545?

**Comment by phil-lopreiato** [comment]
This one seems to be fixed, save for the parts that are out of scope for now (see #567). Closing
