### ISSUE TITLE
Top OPRs Doesn't Show Team #s

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#568]
Otherwise we don't know which team has the lead

![screenshot_20160222-215154](https://cloud.githubusercontent.com/assets/2754863/13240199/a30e3004-d9ae-11e5-844a-0fc00f7d30ed.png)

**Comment by nwalters512** [comment]
Wonder how we never saw this before...

**Comment by fangeugene** [comment]
This is pretty hilarious.
