### ISSUE TITLE
Match video page contents 'stick' sometimes when scrolling

### ISSUE THREAD

**Issue by IAmAGitNewbie** [the-blue-alliance/the-blue-alliance-android#574]
I upgraded to 3.1.0, cleared my cache and then started using the app.  I eventually got to the point where the match video page looked like an MTV flashback:

![tba_screenshot_04](https://cloud.githubusercontent.com/assets/2994465/13276793/1889b20a-da80-11e5-805a-24d975eb88da.png)

The steps I took to get there (twice) were the following:
1: Start the app
2: From the 2016 Events view I select the Week 0 Offseason event in Merrimakc NH
3: Slide over to the teams list and selecte Team 125
4: Slide over to their matches and selected any of the video play options.  (For the screenshots I selected Qual 3)
5: The match info displays at the top and the available videos appear below just fine eventually.
6: I start to scroll the display up to see all the video choices available.  That is when a copy of the original the contents appear to "stick" in the background while contents scroll up:

![tba_screenshot_02](https://cloud.githubusercontent.com/assets/2994465/13276854/c19930b4-da80-11e5-8707-599bd0afacdd.png)

A little further gets me to:

![tba_screenshot_03](https://cloud.githubusercontent.com/assets/2994465/13276861/cf87a782-da80-11e5-9a2c-5984d77a7b90.png)

If I keep scrolling I get to the screenshot at the top.   This reproduced 2 out of 3 times I tried it on my Samsung G6.

2 observations that may be relevant:

1: The video thumbnails took a while to load a couple times I was trying (and once when trying to reproduce).
2: One of the reproduced times my phone switched from Wi-Fi to 4G (stupid hospital Wi-Fi!). I noticed this because that time I did not get video thumbnails like the other times.

**Comment by nwalters512** [comment]
What even...

Sadly I can't reproduce this on my Nexus 5 running 6.0.1. Which version of Android are you running?

I'm tempted to chalk this up to Samsung's incompetence, but it's still definitely worth investigating, especially considering how many people use Samsung devices.

What I really need to see is your view hierarchy to figure out if this is a rendering bug or there really are two copies of everything on-screen. You have three options:

1. (Easiest) Go to System Settings->Developer Settings->Show Layout Bounds, return to the app, and reproduce your third screenshot with that setting on
2. Use the Android Device Monitor and take a screenshot; figure out if there's a way to export the associated view hierarchy.
3. Clone the latest master, open in Android Studio, build and install a debug version of the app. Using the Stetho debugger in Chrome, get a copy of the view hierarchy (I think it's in the "Inspect" tab of the Chrome debugger) and post it here.

**Comment by IAmAGitNewbie** [comment]
Im running 5.1.1 on a Galaxy S6 (Verizon variant). 

I enabled displaying the layout bounds and Im trying to reproduce yet again.  I will post an update with screenshots if I can.  (Im now @ home and not on the crappy hospital Wi-Fi which may be a factor)

**Comment by IAmAGitNewbie** [comment]
As requested:

![tbascreenshotdebug01](https://cloud.githubusercontent.com/assets/2994465/13277334/69abd230-da85-11e5-9dc4-5e8779779049.png)

and:

![tbascreenshotdebug02](https://cloud.githubusercontent.com/assets/2994465/13277338/76e65100-da85-11e5-827c-f88074c45f02.png)

This time I watched the last video from Qual 3 all the way through in full screen mode (landscape).  Once it ended the YouTube app moved it to a thumbnail in the lower right corner and displayed the regular YouTube app main page.  I backed out back to TBA and I see nothing except whilte and the star in the lower right corner:

![tbascreenshotdebug03](https://cloud.githubusercontent.com/assets/2994465/13277423/f7197d3e-da85-11e5-8684-f320d73e16d8.png)

Once I rotate back to portrait I can reproduce the failures you see above.

**Comment by IAmAGitNewbie** [comment]
I am starting to suspect it has something to do with the change in orientation before returning to TBA from the YouTube app.

I can reproduce easily when I shift into landscape mode to watch a video and then return to TBA while still in landscape.  The video does not need to finish, the phone simply needs to still be in landscape mode.  I always wind up with the blank view (see last screenshot above) when I do that.  

Once I swap back to portrait mode it happens 100% of the time now no matter what video I watch.

**Comment by nwalters512** [comment]
Weirdly, it's definitely something to do with orientation changes. I can easily reproduce it now with the steps you gave. Thanks so much, I'll investigate.

**Comment by nwalters512** [comment]
I can actually reproduce this by changing the orientation without even leaving the app. Thankfully this seems to be the only activity in the app affected by this.

**Comment by phil-lopreiato** [comment]
I can reproduce this as well. Nexus 5X, Android 6.0.1

It looks like there's a second copy of the layout on top of the first one and that's what gets scrolled. 

I can also reproduce the blank screen after leave/orientation change. There, maybe we need to rebind on resume?

**Comment by nwalters512** [comment]
The landscape issue is caused by us being dumb: [layout-land/activity_view_match.xml#L14](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/res/layout-land/activity_view_match.xml#L14)

The duplicate layout issue is more mysterious.
