### ISSUE TITLE
"Upcoming match" notification text should be revised

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#583]
Currently reads something like "Match SCMB Q7", should really be "SCMB Match Q7". While we're at it, we should check all the notification text to make sure it looks good.

**Comment by 1fish2** [comment]
I forgot if I wrote it that way to fix the ambiguity (Q7 at which event?)
across the board with minimum risk during competition season or to make the
messages structured (logically, the full event name is 2016-SCMB-Q7;
obviously the year matters for historical stats but not for notifications).

Hypothesis: Many of the people who use notifications receive multiple
notification types about multiple teams at multiple events during a weekend
and sometimes watch simultaneous webcasts via the GameDay page. They need
notifications that are unambiguous, concise (one-line messages don't get
collapsed), and not taxing to understand while busy watching 1-3 webcasts.
Not all of us are great multitaskers. Simple templates are easier to parse
than English prose.

Usability testing could validate or disprove this or compare alternate
phrasing. E.g. use the Python script to show example messages to a few
people from the target audience while they watch recorded match videos. Can
they figure out a message the first viewing and quickly understand it in
repeat viewings?

I'm fine with the suggestion, i.e. "Starting soon: SCMB match Q7" but will
all the event names and notification types fit on a line? How about
"Starting soon: SCMB-Q7"?

Notifications like "Teams *111*, 222, and 3333 scored 176 vs. 444, 555, and
6666 scored 88" would benefit greatly from bolding the team numbers that
you're following. Is bold achievable in a notification?

**Comment by nwalters512** [comment]
I'd be in favor of your suggestion "Starting soon: SCMB-Q7". Most people should understand that means a match is starting soon, so labeling it explicitly as a match is probably unnecessary. It would be nice to do user testing with a few of these variants though.

It looks like we have limited control over how notification text is styles, so bolding should be possible: http://stackoverflow.com/questions/23917127/how-to-highlight-left-hand-side-text-of-every-line-in-notification

**Comment by 1fish2** [comment]
Cool. I can probably get on it this weekend. If someone else wants to do it
before then, just call dibs.

**Comment by phil-lopreiato** [comment]
Ideally we can ship a fix for week 1 events, that release will have to be Wednesday night at the latest. 

@1fish2 is that too soon for you?

**Comment by 1fish2** [comment]
Yes, alas, I can't get to it before this weekend.

**Comment by phil-lopreiato** [comment]
Ah, I see.

I can make the quick change to "Starting soon: SCMB-Q7" for this week to clear up the initial ambiguity. Can you still take a look at bolding followed teams (probably just have to `@Inject SubscriptionsTable`) and/or some other improvements?

**Comment by 1fish2** [comment]
Yes. Let's split out the changes for next week into a separate issue, and
I'll take that one.

I haven't looked at the code base since the redesign. Can you point me to
docs on the dependency injection and other changes?

**Comment by phil-lopreiato** [comment]
We use [dagger2](http://google.github.io/dagger/) for dependency injection, it's a really cool premise. 

You'll probably want to change the signature of [`buildNotification`](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/gcm/notifications/BaseNotification.java#L70) to also take an instance of the database table. Then you could inject it into [`GcmMessageHandler`](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/gcm/GCMMessageHandler.java#L53) pass it to the other method.
