### ISSUE TITLE
Bolded teams in notifications should be based on Favorites, not Subs

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#630]

**Comment by 1fish2** [comment]
Please say more.
I had it bolding both favorites and subscriptions until Phil pointed out that only subscriptions cause notifications.

**Comment by fangeugene** [comment]
Only subscriptions cause notifications, but if a favorited team is also in the match, I would like to see it bolded as well.

**Comment by 1fish2** [comment]
So back to favorites + subscriptions. OK.

How about in Recent Notifications? I'd like to bold the same team numbers there.

**Comment by fangeugene** [comment]
Throughout the app, wherever a Favorite team shows up, it should have something (bold, underline, etc.) that highlights it. Whether that's a notification, match list, team list, award, etc.  That should go under a different Issue though.

**Comment by 1fish2** [comment]
I believe navigating from a Team to Matches will bold that team's number throughout the list. Would you like it to underline the other favored + subscribed teams in the list?

**Comment by fangeugene** [comment]
On the website, underline is currently used when navigating from Team to Matches. Maybe we can put a small green green dot in the upper right corner of a team's cell in the match table if it's a favorite?

I can't think about this too much right now, I have some work I need to do. We should figure out a good UI.

**Comment by nwalters512** [comment]
I like the idea of a dot. It's unobtrusive and wouldn't conflict with existing text formatting.

If we want to do this everywhere, we'd have to make sure checking if a team is favorited is incredibly fast. Even if a single query takes 1ms, 6 teams * 100+ matches = 600ms. If that happens on a background thread, it's probably fine. Just something to look out for.

**Comment by phil-lopreiato** [comment]
A dot would work, I think. We'll have have to take care of performance, like Nathan said. Rendering the match results is already one of the slowest renders we have (and one of the few to regularly cause frame drops). 

Maybe we should move that to RecyclerView first?

**Comment by nwalters512** [comment]
Yeah, we can look into recycler view for that. I don't think recycler view is the silver bullet for performance issues though. Maybe there's some  optimizations we can do in the rendering steps.

**Comment by 1fish2** [comment]
A yellow star to indicate a favorite would be more self-revealing by tying
back to the UI for marking favorites.

It'd be great to see a match schedule with all the favorites indicated.
Even better to print one via CloudPrint or from the web site.
