### ISSUE TITLE
Can you add Samsung's API for Samsung Devices to have LED notifications?

### ISSUE THREAD

**Issue by gofirst2220** [the-blue-alliance/the-blue-alliance-android#632]
See title. Most of the apps has the option to use the LED notification incidator on some devices like Samsung variants. Does this app have the option to do so, including changing the LED notifications colors to differ from other apps? If not, please add it in next release.

Android Version: 5.1.1
Device Variant: SM-G920A
Device Name: Galaxy S6
Manufacturer: Samsung
Carrier: AT&T

**Comment by nwalters512** [comment]
This is actually part of Android's notifications API: http://developer.android.com/reference/android/app/Notification.Builder.html#setLights(int,%20int,%20int). It should be easy enough to add to a future release.

**Comment by gofirst2220** [comment]
Ah. I assumed it's Samsung specific because most of display, scrolling, etc requires Samsung API to its drivers. I never noticed LED notifications are Android API.
