### ISSUE TITLE
I checked the Central Illinois Competition page in the app...

### ISSUE THREAD

**Issue by gofirst2220** [the-blue-alliance/the-blue-alliance-android#633]
See title. How come the website has updates with no live stream from UStream channel but the app has no data from the competition?

**Comment by nwalters512** [comment]
The event has no data to report yet except the list of attending teams. The match schedule probably won't be posted until tonight, and qualification matches don't begin until tomorrow. Sadly, we don't yet have the ability to fetch data from the future :smile:

**Comment by gofirst2220** [comment]
Ah. Wouldn't you extract data from the ranking table from FIRST official ranking site, which almost always has the schedule and latest info? Which I always frequently access for last 4 years from my old Windows Phone until Dec of 2015, in which I just switched to Android. If not, the live stream is already up and running for the event as a test until the qualification rounds starts.

**Comment by nwalters512** [comment]
We do pull data from FIRST. But if FIRST has no data, there's not much we can do. You can see all the official FIRST data at http://frc-events.firstinspires.org/2016/ILPE. The event hasn't started yet, so there's not much data available save for venue information and the team list.

**Comment by gofirst2220** [comment]
Ah. The last time the source, I used to use for like last 4 years before end of 2015, a official website with basic HTML table that they kept updating after each match at Lake Superior Competition. I didn't know Central Illinois has better site.

**Comment by nwalters512** [comment]
Yeah, FIRST updated their event pages this year, they're much improved.

I'm closing this since it isn't actually an issue.
