### ISSUE TITLE
“No alliance data found” after receiving “Alliance selections updated” notification

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#638]
This happened last week for the CAMA event and again today for the WAELL event.

Steps:

1. Receive and open an “Alliance selections updated” notification. (I did this a while after the notification arrived.)
2. Tap through to see the alliance selections.<br/>
--> It showed “No alliance data found”!
3. Tap MATCHES.<br/>
--> It already had results for several QF matches.
4. Tap back to ALLIANCES.<br/>
--> It still showed “No alliance data found”.
5. Tap the refresh button a lot.<br/>
--> About 1/5 of the time it would flash the alliance selections briefly, then erase it. I could read the first team captain number (3711) before the contents disappeared.
6. Try [www.thebluealliance.com](http://www.thebluealliance.com/event/2016waell) <br/>
--> It did show the alliances.

Currently running App Version 3.3.0, build 3/17/16 11:21 PM, commit 22ce4b7. I did not have a laptop at hand to try debugging tools.

**Comment by nwalters512** [comment]
Can confirm for Central Illinois as well.

**Comment by fangeugene** [comment]
It's server side api caching.

**Comment by 1fish2** [comment]
The app could repeatedly flash the right data on screen before hiding it. Doesn't that rule out the cache hypothesis?

What determines whether a `DatafeedFragment` displays `mNoDataBinder`?

**Comment by phil-lopreiato** [comment]
Now that I'm no longer swamped/exhausted (man, back to back regionals is tough)...

Binders determine if the data they've received is valid and display the NoDataBinder if not. Example: https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/binders/ListViewBinder.java#L78

**Comment by 1fish2** [comment]
While it used to briefly flash the (AFAICT correct) alliance selection data then switch to “No alliance data found”, now it steadfastly shows “No alliance data found”.

This continued for 42 minutes yesterday, which must be longer than cache timeouts.

Timeline:
* Subscribed to upcoming-match notifications and match-score notifications for FRC 1114, and (IIRC) not to alliance-selection notifications.
* ~1:22 PM ET received a notification for upcoming match Waterloo QF1-1 scheduled for 1:30.
* The Matches tab displayed the entire QF match schedule (one could derive the alliances from that, if the tournament rules don't change) but the Alliances tab showed “No alliance data found” despite repeated taps on the reload button.
* I tuned in to the webcast.
* After the match and long judge deliberations [to decide whether to give a yellow card for flipping a robot???], the score was announced at 1:45, the match-score notification arrived, and the Matches tab displayed the QF1-1 score. Still “No alliance data found” in the Alliances tab.
* Still “No alliance data found” at 2:04, despite more taps on the reload button, well after QF2-1 results were announced and displayed in the Matches tab.
* Then I let the phone's display go to sleep. A couple minutes later I woke the phone, and now the Alliances tab displayed the alliance list.

This was on a Nexus 5X running Android 6.0.1.

**Comment by phil-lopreiato** [comment]
So I learned today that the FRC API doesn't populate the alliances endpoint until the first QF match has been played (see https://github.com/the-blue-alliance/the-blue-alliance/issues/1456), so the sequence of events you're seeing may actually be correct.

I was watching two events today (CTHAR and MABOS) today, and the alliance updated notification went out after QF1 and QF2 scores were posted, respectively (which means TBA didn't have the data until then).

Next time you see this, can you check if TBA on the web displays the alliances? That will help us figure out if it's an app databinding problem or not.

**Comment by 1fish2** [comment]
I'll check next time.

Note that in the CAMA event (see the first post in this issue), www.thebluealliance.com did show the alliances when the app did not -- but the code has changed since then.

**Comment by phil-lopreiato** [comment]
Right, I think there actually multiple issues in play, and which one we see depends on the timing of events.

 - The alliance selected notification [contains the alliance info](http://www.thebluealliance.com/apidocs/webhooks#notification_alliance_selection), which gets written locally when it's received. 
 - On the server, when the alliance data gets updated, a task is enqueued to clear the API caches. This isn't instantaneous, as there may be other tasks in the queue.
 - If you directly open the link from the notification (pre 9f12359), there's a chance that the new data has been stored locally, but the cache clearing task hasn't yet so you'll see the app flash between the data and the no data view, since the TBA API is still returning a cached endpoint with no alliances present. After 9f12359, the no data view shouldn't override the local data.
 - However, if TBA doesn't have alliance data (due to the reasons in my last comment), then there's nothing to display in the first place. 

So it seems like this issue depends on a number of things. Make sense?

**Comment by 1fish2** [comment]
Yes. That's much clearer.

So we need to test this when and when not subscribed to an event's alliance-selection-notifications.

Do you want to add log messages for this? Next weekend I can watch adb logcat while following Silicon Valley Regional (with alliance-selection-notifications) and another event (without).

**Comment by phil-lopreiato** [comment]
Sounds like a plan. You can also verify when TBA received alliance data by watching the firebase ticker for when the alliances updated notification is sent.

At what point(s) in the above process would it be most useful to have a log?

**Comment by 1fish2** [comment]
Great idea. Should I watch the Ticker column in the app or on the GameDay page?

Alas, yesterday's Waterloo Ticker doesn't go back far enough to show QF1 or alliance data arriving.

Which data arrives by Firebase vs. GCM vs. API calls? Or do Firebase notifications arrive by GCM?

**Comment by 1fish2** [comment]
Logging ideas:
* Retrieving alliance data for event X and whether the data was {unavailable, from the local cache, from the server API}.
* Storing alliance data into the local cache from GCM vs. Firebase vs. server API result.
* If not taken care of by the Firebase ticker: The receipt of QF1-1 starting-soon and match-score info.

**Comment by phil-lopreiato** [comment]
The firebase ticker is actually totally independent of the other datafeed - no data there is stored locally. However, the TBA server pushes all notifications it sends to firebase pretty much instantly, and it updates everywhere in real-time (that's the main benefit of firebase). All non-firebase data you see comes from the TBA API, except that incoming GCM notifications can overwrite the local storage, where applicable. 

Since firebase updates in realtime, it doesn't matter where you watch from. It might be easier to watch in the app, since you can watch the ticker for only one event there.

**Comment by phil-lopreiato** [comment]
Actually, I don't think I was to add logging into the prod app to track this - it just feels messy and we can debug the same/better with our existing tools.

Let's watch the firebase ticker and the db/network calls via stetho (you can see directly what's stored locally, as well as what the API responses are). I think that's the better way to approach this. 

Let's revisit on Saturday (also depending on what changes FIRST makes for this weekend, if any)

**Comment by 1fish2** [comment]
That's cool but I don't see the release build in stetho.

**Comment by nwalters512** [comment]
Stetho is only enabled for debug builds: https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/TBAAndroid.java#L49

**Comment by phil-lopreiato** [comment]
Oh, I thought you'd be at home with the ability to do a debug build. Want me to build you one to use on the go?

**Comment by 1fish2** [comment]
I'll be at home and can run a debug build with Android Studio and stetho *but* I don't have a custom server to get it notifications to insert alliance data into local storage.

If the notification data pathway is unimportant, I'm all set with a debug build. I can watch notifications in the release build on one phone, watch the data in the debug build on a second phone, and watch the Firebase ticker on either.

Does it still take a LOT of setup to get a custom server and GCM notifications?

(FYI I'm following SVR and the PNW District Championship this weekend.)

**Comment by phil-lopreiato** [comment]
I don't the the notification data pathway is the most important here, I think it's the least likely to be causing the issues. 

And yes, it's still a pain to roll your own push notifications. Unfortunately, there really isn't a good way to do it

**Comment by 1fish2** [comment]
This could be another case, or maybe just a cache problem: GCM notification for Awards posted but the app doesn't show them (even 40 minutes later) while the web site does.

1. Release builds on two Androids received GCM notification arrived for `2016casj` awards but their app's Awards tab didn't list any awards.
2. I started the Debug app (from master as of d72bb7b022) and connected stetho.
3. Stetho shows it fetched `https://www.thebluealliance.com/api/v2/event/2016casj/awards` with no cache control headers except `If-Modified-Since:`, receiving a 304 response dated `Sat, 09 Apr 2016 02:02:50 GMT`.
4. It also fetched
    * `https://www.thebluealliance.com/api/v2/event/2016casj/stats` getting HTTP 200,
    * `https://www.thebluealliance.com/api/v2/event/2016casj` getting HTTP 200,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/matches` getting HTTP 200,
    * `https://www.thebluealliance.com/api/v2/event/2016casj` a second time receiving an HTTP 200 response with the same date,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/rankings` getting HTTP 200,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/district_points` getting HTTP 200,
    * and `https://www.thebluealliance.com/api/v2/status` getting HTTP 304.
    * All of those replies have `date:Sat, 09 Apr 2016 02:02:50 GMT` except the last one with `date:Sat, 09 Apr 2016 02:02:51 GMT`.
5. I navigated to the 2016 SVR event's Awards screen.
6. The app made these queries, all of them returning HTTP 200 responses with `date:Sat, 09 Apr 2016 02:03:33 GMT`, and all getting `cache-control:public, max-age=61` unless otherwise listed:
    * `https://www.thebluealliance.com/api/v2/event/2016casj` this time with `Cache-Control:no-cache`,
    * the same request 39 msec later according to the `OkHttp-Sent-Millis:` header,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/teams` with `Cache-Control:no-cache` and getting `cache-control:public, max-age=86400`,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/awards` with `Cache-Control:no-cache` getting `cache-control:public, max-age=3600` *[Is this why it wont update?]* and the response data `[]`,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/stats` with `Cache-Control:no-cache`,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/matches` with `Cache-Control:no-cache`,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/district_points` with `Cache-Control:no-cache`,
    * `https://www.thebluealliance.com/api/v2/event/2016casj/rankings` with `Cache-Control:no-cache`.
8. [TBA website](http://www.thebluealliance.com/event/2016casj#awards) does display 3 SVR awards.
9. The `awards` DB table is empty and the Awards tab says `No awards found`. (The Release build on two other Androids display the same thing, despite receiving the `Event awards have been updated` GCM notification and tapping the Awards refresh button, even 40 minutes after the GCM notification. These Androids were not displaying the Awards tab ahead of time.
10. Tapping "refresh" finally received the 3 awards with response `date:Sat, 09 Apr 2016 02:46:55 GMT`. (That's 44 minutes after the first request under stetho.) It stored the 3 records in the `awards` table and displayed the info in the Awards tab.

**Comment by phil-lopreiato** [comment]
I hate caching.

**Comment by 1fish2** [comment]
Alas, another case of flashing up the new data then switching back to old data: Perhaps an hour after the final day's awards were posted for 2016pncmp, going to that screen in the app flashed up the full awards list (starting with 3 regional chairman's awards), then replaced the contents with the short list of ~3 awards from the previous day.

Then it indicated another auto-refresh by changing/animating the refresh button, then stuck with the short list. Tapping refresh didn't help.

**Comment by 1fish2** [comment]
A weird thing about the match case: When refreshing a quals screen fails to get the now-available scores & breakdown, navigating "left" to the match-list does retrieve those scores (and breakdown, although not displayed), but the data doesn't get into the `matches` table and tapping through to that quals screen doesn't fetch it.

**Comment by phil-lopreiato** [comment]
I'll bet the awards thing is also due to a longer cache timeout on the server (on my phone, so I can't check). 

I'm also trying to think about the root cause to these issues, and am slowly coming to the conclusion that it's going to be a summer project to fix (fixing it properly is going to be a much larger change than I'd be comfortable deploying mid-season). I want to talk in slack about ways we can mitigate it though

**Comment by 1fish2** [comment]
@phil-lopreiato's hypothesis explains most of this behavior very well: Models (DB rows) can be updated from multiple sources (push notifications and multiple API endpoints) which could be at different cache states (different age towards expiration). The server currently sets some cache timeouts (like awards) to 3600 seconds. When this issue was first filed, it set a 3600 second timeout to matches.

Thus:

1. If the user navigates to the Quals 2 match screen before that match's scores are posted, the app will fetch `match/2016casj_qm2` and get `-1` scores. That data will (currently) have a max cache age of 61 secs. After the match scores are posted, refreshing that match screen won't get new data until the 61 seconds expire. 
[Q: Is it even worse than that? Can it get a 200 result with the same data and a new Last-Modified and a fresh 61 sec expiration?]
2. Navigating to the Matches screen will now fetch `event/2016casj/matches`, which will fetch fresh data since the user was viewing another screen for > 61 seconds. The response will include all the match scores and breakdowns available so far, including `qm2`, and all that data will go into the local DB.
3. Navigating to the Quals 2 match screen will fetch the `qm2` results from the DB, display it, re-fetch `match/2016casj_qm2`, get the old cached data from some node in the network, and go back to displaying the time instead of the score. Thus the flash and revert.
4. The Quals 2 match screen won't fetch the `qm2` results until at least the original 61 seconds expire (used to be 3600 secs); possibly not until the most recent request expires.

This hypothesis does not explain:
* A zeroed score breakdown, https://github.com/the-blue-alliance/the-blue-alliance/issues/1463
* Other discrepancies having scores XOR having a score breakdown. A separate bug? How to reliably reproduce it?
* Are there cases where a request with `cache-control: no-cache` gets old data with a new `Last-Modified` timestamp? How should the client set cache control other than `If-Modified-Since`?


We could test this hypothesis either by (1) debug-logging when the app overwrites data along with the old & new data and the Last-Modified timestamp from the network request, or (2) making a partial or complete fix and testing if it works, or (3) ...?

(Another hypothesis is a bug in one of the libraries like rxandroid, but that's not a specific explanation.)


It'd help to have a way to reproduce the problem without a live event, even if that's a temporarily-modified local server and some stetho work. The ideal would be a way to unit test this.


Fix ideas:

1. Make the server set the max-age for all responses to at most 61 secs during a live event. Allow a much larger max-age for other events. Define "live event" by something like "happening today in that event's time zone."
1. Ensure that the server timestamps data when received from FIRST and puts those timestamps in the Last-Modified header of each API reply and includes it in push notification bodies. Make the client store this info in each table row and not replace any row that has a newer timestamp. If we can't yet get a Last-Modified into push notifications, make the client timestamp that data when received, and worry later about delays, esp. Doze mode.
    * What's the impact of comparing Last-Modified by `<` rather than only `!=`?
2. If the client can't get good timestamps, use data-specific checks to avoid going backwards. E.g. don't replace positive match scores with `-1,-1` scores and don't replace an awards list with a shorter list -- except perhaps when the new data has a much later timestamp, say 2 hours.
3. Consider making the "refresh" button bust caches via a random query parameter. A user tapping the "refresh" button is trying to fetch an update.
