### ISSUE TITLE
Incorrect Stats - Event Stats

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#652]
For [2016 Sacramento](http://www.thebluealliance.com/event/2016cada#event-insights) stats, the Android app says High Score Quals: 162 in Q22 (correct), Playoffs: 172 in QF1-1 (no, that score was surpassed by 205 in SF1-1 and 192 in F1). The [Insights](http://www.thebluealliance.com/event/2016cada#event-insights) web page is correct.

Other stats differ between the Insights web page and the app's Event Stats, esp. Playoffs stats such as

> Average High Goals: 6 in the app, 4.91 on the web site
Average Win Margin: 101 in the app, 56.69 on the web site
Average Foul Score: 0 in the app, 3.59 on the web site
Low Bar # Damaged / # Opportunities: 2 / 2 in the app, 30 / 32 on the web site

**Comment by fangeugene** [comment]
I think this is a API endpoint cache clearing issue. Will look into it.

**Comment by 1fish2** [comment]
It's maybe 16 hours after the last match. Stuck cache?

**Comment by fangeugene** [comment]
https://github.com/the-blue-alliance/the-blue-alliance/issues/1434

**Comment by phil-lopreiato** [comment]
Should be fixed server-side in https://github.com/the-blue-alliance/the-blue-alliance/commit/548221563751d8945ee06bf4ae1465e8bbf69681
