### ISSUE TITLE
Updates for API 24

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#663]
This is a place to list all the things we have to fix before we're ready to target N. These can be broken out into individual issues as needed.
- [ ] Onboarding breaks if we enter multi-window mode while data is loading
- [ ] In multi-window mode, we can transition paused->resumed->paused->resumed->etc very frequently. We can no longer afford to reload data whenever our fragments transition back to resumed. Need to figure out how to handle this nicely.
- [ ] We need to be better about saving state throughout the app. Because activities are recreated every time the multi-window is resized, we want this to be as seamless as possible for users
- [ ] All activities with a myTBA FAB should cache the preferences shown in the list; if you open the model settings and resize the window with the settings open, the list reloads, which isn't a very nice visual effect

**Comment by phil-lopreiato** [comment]
The N API was finalized recently, [here is the list of new things](https://developer.android.com/preview/api-overview.html)

## [Behavior Changes](https://developer.android.com/preview/behavior-changes.html)
It doesn't seem like there's too much here, thankfully. 
 - [ ] Doze is more aggressive about disallowing background tasks. We should [double check we're doing everything right](https://developer.android.com/training/monitoring-device-state/doze-standby.html)
 - [ ] Other Background Changes. [We need to make sure nothing breaks](https://developer.android.com/preview/features/background-optimization.html)

## New Features
 - [ ] [Multi-window](https://developer.android.com/preview/features/multi-window.html) is a thing. There are lots of compatibility issues here.
 - [ ] New notification libraries. The only one that affects us is [bundled notifications](https://developer.android.com/preview/features/notification-updates.html#bundle), I think
 - [ ] [Scoped Directory Access](https://developer.android.com/preview/features/scoped-folder-access.html) seems like a good idea for robot images
 - [ ] [Constraint Layout](http://tools.android.com/tech-docs/layout-editor) (not tied to SDK 24, but new and a good idea) to reduce view depth

**Comment by nwalters512** [comment]
In terms of Background Optimizations, the following does apply to us, as we use a broadcast receiver to monitor network changes:

> Apps targeting the Preview do not receive CONNECTIVITY_ACTION broadcasts if they register to receive them in their manifest. Apps that are running can still listen for CONNECTIVITY_CHANGE on their main thread by registering a BroadcastReceiver with Context.registerReceiver().

For Doze, the only thing that really needs to be done is to ensure that all notifications are being sent with high priority.

Multi-window unfortunately doesn't play extremely nicely with how we've architectured the app. That will take some effort to get right.

**Comment by phil-lopreiato** [comment]
Hopefully nothing major breaks, but we can file further issues as they arise
