### ISSUE TITLE
[finally] Dynamic Tab Strips

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#706]
Something we've wanted to do for a long time...

This way, we can only show tabs we have data for (so for events in the future, only show info & team list, for example).

If we [base the tab strip on RecyclerView](https://github.com/nshmura/RecyclerTabLayout), then we should be able to add/remove things from the adapter on the fly and just call `notifyDatasetChanged`. We'll have to make sure we don't cause weird `ViewPager` memory leaks though

**Comment by nwalters512** [comment]
IIRC, the issue was dynamic tabs was with the pager adapter, not the tab strip. Adding/removing from a fragmentpageradapter is messy.

**Comment by phil-lopreiato** [comment]
Ah, that does sound familiar, because `ViewPager` holds some references. I still can't believe this hasn't been made easier yet...

**Comment by phil-lopreiato** [comment]
Continued from #741... (cc @1fish2)

> Workaround idea 1: Recreate the pager when it needs to add tabs. (Issue: Losing the current tab's contents.)

This will also recreate all the fragments involved (unless we wrote some way to save them). I don't think this is what we want, because it'll be a pretty big performance hit

> Workaround idea 2: Create the pager with spare tabs, hide them by limiting scrolling, and use them as needed.

You can't hide tabs either :(

The thing is, we'll have to find a way to update a `ViewPager` and its adapter dynamically. It's harder than you thing - google around for it and see if you can find any new solutions

**Comment by nwalters512** [comment]
I have an inclination to just write a custom component that does what we want - although the fact that no one's already done that means it might not be too easy :/

Our next great library: Tabby McTabface?

**Comment by phil-lopreiato** [comment]
If we do that project (you in the mood for a big summer refactor?) - I say we work towards ditching fragments entirely. See the "Deep in Fragment Spaghetti" section of [this article](https://corner.squareup.com/2014/10/advocating-against-android-fragments.html) and let's take a look at integrating [mortar](https://github.com/square/mortar) with our Subscriber/Binder framework

**Comment by 1fish2** [comment]
> This [recreating the pager when it needs to add tabs] will also recreate all the fragments involved (unless we wrote some way to save them). I don't think this is what we want, because it'll be a pretty big performance hit

It only takes a fraction of a second to switch years so a "switch" to reload the current year would be fine in the rare case when there are tabs to add, and certainly better than failing to add them (#741). Nested tab levels would reload even faster. **But** it'd be disruptive and annoying to discard the user's current navigation position when a new tab's worth of data arrives.

Does adapting to Android N multi-window mode have implications for Tabby McTabface?

**Comment by phil-lopreiato** [comment]
> It only takes a fraction of a second to switch years so a "switch" to reload the current year would be fine in the rare case when there are tabs to add, and certainly better than failing to add them

True, and I guess obliterating the top level fragment and recreating it is an approach we can take. Although again, issues will exist with the data lifecycle - we don't want to block until the network call finishes. The tabs are actually loaded from the db (even though a network call is fired/stored), which is why you need to refresh + restart the app to actually see changes. 

Plus, we'd have to make sure there are no memory leaks, because I don't trust that there aren't.

**Comment by 1fish2** [comment]
You needn't restart the app to see the changes after Refresh. Just set the year pop-up from "2016 Events" to "2015 Events" and back. That rebuilds the tabs and their contents.

So when loading DB data makes it need to add tabs, can it do likewise as a workaround? Why would that leak more memory or block the UI more than setting the year does?

**Comment by phil-lopreiato** [comment]
> Why would that leak more memory or block the UI more than setting the year does?

It would leak the same, which I'm not sure is zero. The lifecycle is pretty hacky and confusing, and I wouldn't want to make our existing OOM problems worse by adding them into an action that happens a lot more frequently than switching years.

Of course, this isn't a deal breaker, just something I'd like to confirm isn't a problem before we get in too deep.

**Comment by nwalters512** [comment]
To me, rebuilding the entire pager on refresh seems like a rather hacky fix to a deeper problem. It would work, but it doesn't address the root problem, which is that we can't easily do dynamic tabs. I'd rather write something that can solve that problem throughout the app.

I'd be hesitant about going all-in with Flow - because for Flow to be really useful, it looks like you really do have to use it for everything. That being said, using Mortar to turn our fragments into "custom views with dependencies" is intriguing.

This is probably going a little off-topic, but I really would like to see a way where we don't have to use the presentational tab components (fragments, views, whatever they end up being) as refresh controllers. I think it would be great to find a way to have the views just automatically update when new or updated data appears in the database and delegate the fetching of new data to other components.

**Comment by phil-lopreiato** [comment]
> That being said, using Mortar to turn our fragments into "custom views with dependencies" is intriguing.

This does seem like a good place to start, and it can evolve into a more "all in" approach if it solves our problems well. 

> This is probably going a little off-topic, but I really would like to see a way where we don't have to use the presentational tab components (fragments, views, whatever they end up being) as refresh controllers. I think it would be great to find a way to have the views just automatically update when new or updated data appears in the database and delegate the fetching of new data to other components.

[Square is on fire](https://github.com/square/sqlbrite) 🔥 🔥 🔥

**Comment by nwalters512** [comment]
Is there anything Square doesn't have a library for 😛

**Comment by 1fish2** [comment]
SQLBrite sounds nice but dosn't RxJava handle that when data changes arrive from the network or UI?

Square has 9 GitHub pages of libraries, including FFT code, but where's their machine learning library?

**Comment by phil-lopreiato** [comment]
> SQLBrite sounds nice but doesn't RxJava handle that when data updates arrive from the network or UI?

SQLBrite provides Rx bindings for the Android database - that is, we could perform a query and get an observable back, instead of constructing one ourselves (which is a ton of boilerplate, look at [this](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/datafeed/APICache.java)). 

It also provides the benefit of subscribing to all future database updates, so a view could just run a db query and subscribe to it. Then, it would show data locally and when new data comes in from the web, it gets written to the db and propagated to the views automatically. It can probably simplify some of the refresh logic and help keep the callbacks straight, as well.
