### ISSUE TITLE
Suggestion: Show Ranking Points/Match

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#728]
Like [TBA Web # 1465](https://github.com/the-blue-alliance/the-blue-alliance/issues/1465) so you can tell how your team is really stacking up in seeding.

If it doesn't claim to be a "ranking" then it won't confuse people about the difference vs. official rankings.

How to convey what this value is for?
It's a derived value, not an official FIRST value, so would it bother people on the Rankings screen?

**Comment by nwalters512** [comment]
I like this. We could put this in the "Stats" tab, since we already built features for providing explanations (if people wonder why RP's/Match are significant) and sorting.

**Comment by 1fish2** [comment]
This feature has been implemented for TBA web site in #1573 , yay!

**Comment by phil-lopreiato** [comment]
Still something we'll need to expose in the app (since it's not a part of the ranking data that is in the API), but baby steps :)

**Comment by phil-lopreiato** [comment]
With apiv3, we have better knowledge of which rankings items are "primary" for that season, so we can calculate the first order sort divided by matches played.
