### ISSUE TITLE
Add more off season events like Minnesota State FRC Championship

### ISSUE THREAD

**Issue by gofirst2220** [the-blue-alliance/the-blue-alliance-android#741]
Minnesota State Robotics Championship is usually around few weeks after world's, like today. I'm sure there are other off season events that happens between the week 6 and next year's kick off. So, why not those competitions are added yet?

**Comment by phil-lopreiato** [comment]
That event [already exists on tba.com](http://www.thebluealliance.com/event/2016mnsc), which is the same data the app uses (hit refresh if you don't see it)
![screenshot_20160521-110745](https://cloud.githubusercontent.com/assets/2754863/15449181/6e8049a4-1f44-11e6-8ba0-2a7dec289158.png)

If you don't see an event on the site you'd like to have, please open an issue [in the data repo](http://github.com/the-blue-alliance/the-blue-alliance-data) or post in the [Facebook group](https://www.facebook.com/groups/moardata) and one of the admins will get to it.

**Comment by 1fish2** [comment]
**Bug:** Tapping the refresh button makes the spinner spin for a bit... and then nothing happens. I tried digging into a Championship event and back out, and still no off-season events. Selecting "2015 Events" from the menu, then returning to "2016 Events" got them to appear.

**Usability problem:** It's not obvious that you need to tap the refresh button to get the off-season events to appear.

**Data:** 2016 IRI needs to get added to the server's data. Then presumably people will need to refresh again.

**Comment by phil-lopreiato** [comment]
The issue here is dynamic tabs each hosting a fragment. We can't add/remove them on the fly, it seems to be a limitation of the framework/libraries we're using.

@1fish2 do you want to do some research to see if there's a way we can solve this? I've tried and been unable to come up with anything

**Comment by nwalters512** [comment]
That's a known issue. There's no good way to dynamically add tabs to a pager once it's been created.

Hitting refresh to load new data is a paradigm most people are familiar with; I don't think that's an issue.

**Comment by 1fish2** [comment]
Add the deets or add them to the Issue and I’ll poke around.

It’s OK that the user has to manually refresh but the app usually auto-updates, and Refresh rarely helps.

**Comment by 1fish2** [comment]
Workaround idea 1: Recreate the pager when it needs to add tabs. (Issue: Losing the current tab's contents.)

Workaround idea 2: Create the pager with spare tabs, hide them by limiting scrolling, and use them as needed.
