### ISSUE TITLE
[Nougat] Notification Summary Broken

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#774]
At Chezy Champs 2016 today, match scores finally started flowing through to TBA at 19:45 PT, after the event ended for the day. Then match score Firebase Cloud Messages (FCMs) started arriving every few seconds. I watched them arrive on a Nexus 7 Marshmallow tablet and a Nexus 5X Nougat phone.

When I pulled down an FCM's notification view and let the view stay open, when following FCMs arrived, one or both devices played notification tones, Marshmallow accumulated additional lines in the app's notification view, but Nougat did not.

When I swiped away the notification view on Nougat, those additional match-score notification lines never did appear although they are present in the app's Recent Notifications list, and the next incoming FCM would appear as a new notification view.

Apparently, additional info arriving while the app's pull-down notification view is open doesn't successfully add to that view.

**Comment by 1fish2** [comment]
Update: This Nougat bug happens even when the pull-down notification is closed. With an un-dismissed notification, more arriving FCMs don't add to the notification view.

**Comment by phil-lopreiato** [comment]
Yay compatibility bugs (this one falls under #663)... Thanks for reporting!

**Comment by 1fish2** [comment]
Using Nougat's bundled notifications would be nice, but `InboxStyle` notifications should still work.

Go ahead and assign this one to me and I'll look into it this week.

**Comment by phil-lopreiato** [comment]
Awesome, thanks!

I'd guess the bugs starts with how we auto-dismiss the first notification before replacing it?

I believe the group summary is backwards compatible, so it may be worth it to just migrate the whole thing to N notifications and let the fallback do its thing.

**Comment by 1fish2** [comment]
It should arrange for the new notification to replace any previous one, although offhand I forget how that's done. Maybe it shouldn't call `setGroupSummary()` since the app does its own summarization. Moving to N notifications is a fine idea.

**Comment by phil-lopreiato** [comment]
> Maybe it shouldn't call setGroupSummary() since the app does its own summarization. Moving to N notifications is a fine idea.

I think we should let the system handle all the summaries instead of doing it ourselves (assuming it's backwards compatible).

**Comment by 1fish2** [comment]
> I think we should let the system handle all the summaries instead of doing it ourselves (assuming it's backwards compatible).

Yes, I like that a lot but I'd be more I'm comfortable first checking a couple things so we're less likely to leave a bug in the code (e.g. calling `setGroupSummary()`?) that could come back to haunt us.

**Comment by phil-lopreiato** [comment]
> Yes, I like that a lot but I'd be more I'm comfortable first checking a couple things so we're less likely to leave a bug in the code (e.g. calling setGroupSummary()?) that could come back to haunt us.

This is why I really want some testing infrastructure we can spin up to check compatibility. In the meantime, I do have a Nexus 5 running KitKat I can test a pull on.

**Comment by 1fish2** [comment]
Google has a [Compatibility Test Suite](https://source.android.com/compatibility/cts/) and [Firebase Test Lab](https://firebase.google.com/docs/test-lab/).

Sometime we should read up on them and try them out.
