### ISSUE TITLE
Android 7 group summary notifications aren't working

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#793]
When a second or later notification arrives during MadTown ThrowDown this weekend, the notification shade chimes and re-displays the oldest notification that wasn't dismissed instead of accumulating a group summary notification.

(I'll try to debug it when I get a chance.)

**Comment by phil-lopreiato** [comment]
Is there any way we can write tests for actually posting notifications and for the summary logic? I'd much rather be able to know when this kind of thing breaks at the time of the code change

**Comment by 1fish2** [comment]
A debug build (`./gradlew installDevDebug`) of the current `master` code, using `test_notification.py` (at least) works fine right now.

(The Android UI is a little confusing in that it displays a heads-up of just the new notification, and then you can pull down the shade to see the group. If the shade was already pulled down, the new heads-up will merge into it after ~5 secs. -- But I'm pretty sure that's not what I saw last weekend.)

Maybe there's something different between actual cloud notifications to a release build vs. adb `am broadcast` notifications to a debug build that makes the newly added pull-down notification redisplay the first notification rather than display the new one and merge it into a group summary.

Does it matter that `FirebaseNotification.time` never gets assigned, unless maybe by reflection?

The last off-season event will happen this weekend, but it lists no teams. Will it send cloud notifications?

Let's definitely figure out how to write tests for notifications, esp. the net result of Android API calls.

**Comment by phil-lopreiato** [comment]
> Let's definitely figure out how to write tests for notifications, esp. the net result of Android API calls.

I've been doing some research on this, and it doesn't seem like there's a great way to test the result of notifications. The best I've found is the command `adb shell dumpsys notification`, which prints out a ton of info about the currently active notifications. We could write some scripts to send the proper intents to an emulator and verify the right stuff gets created. I'm currently having trouble getting an emulator to work in travis though...

**Comment by 1fish2** [comment]
According to [this SO answer](http://stackoverflow.com/questions/34467310/espresso-test-for-notification-to-showing-up), [UI Automator](https://developer.android.com/training/testing/ui-testing/uiautomator-testing.html) ([see also](http://alexzh.com/tutorials/android-testing-ui-automator-part-4/)) [with Espresso](http://alexzh.com/tutorials/android-testing-espresso-uiautomator-together/) can test notifications. (I haven't read these articles yet.)

**Bigger question:** How to reproduce this bug? Are the script-synthesized CGMs missing any fields? That's my best hypothesis for why the behavior differs.

**Comment by 1fish2** [comment]
Did I mention that `scripts/test_notification.py` doesn't reproduce this bug?

What's different between CGMs from TBA server and the test notifications?

**Comment by phil-lopreiato** [comment]
That's definitely not good... I think that means we'll need a way to keep them in sync. No differences come to mind, so it's probably something pretty subtle.

**Comment by phil-lopreiato** [comment]
I just tried this on current prod by sending a number of match score and upcoming match notifications to my phone from https://www.thebluealliance.com/apidocs/webhooks and the summary notification seemed to work properly. I'll close this now and we can reopen if we see issues Week 1

**Comment by 1fish2** [comment]
It's working fine in the first real events of the season.

**Comment by 1fish2** [comment]
That's one mystery less, to quote [The Hitchhiker's Guide to the Galaxy ](https://books.google.com/books?id=bt0PEsYjj5IC&pg=PA31&lpg=PA31&dq=that%27s+one+mystery+less&source=bl&ots=8VsRBnn_zR&sig=_Oo-xk8vcMBHeyixbs1a81wI5o0&hl=en&sa=X&ved=0ahUKEwj5u8T3-r7SAhUCxWMKHaEtDtUQ6AEIIjAB#v=onepage&q=that's%20one%20mystery%20less&f=false).

I'll at least put forth some hypotheses:

* A bug in Android notifications that was either fixed in a later release (the phone is now running 7.1.1) or reset by a reboot.
* Somehow caused by different data from Chezy FMS.
* Somehow caused by different data from 2016 API v2 vs. 2017 API v3 along with the associated app changes.

<hr>
<img width="572" alt="one mystery less" src="https://cloud.githubusercontent.com/assets/1043120/23585820/bba29540-013c-11e7-872c-c47f3d54091e.png">
