### ISSUE TITLE
Android Nougat compatibility?

### ISSUE THREAD

**Issue by gofirst2220** [the-blue-alliance/the-blue-alliance-android#799]
From the permissions page and the look of the app, it looks and acts like it's made for earlier Android versions such as Marshmallow. Can you guys add more support for Android Nougat?

Device: AT&T Samsung Galaxy S6
Model: SM-G920A
Android OS: Samsung Android Nougat
Android Version: 7.0

**Comment by phil-lopreiato** [comment]
What features are you specifically looking for? I don't have the time to sit down and fix everything that doesn't work with multiwindow. If you or someone you know wants to help contribute, I'm happy to accept pull requests though.

Closing in favor of https://github.com/the-blue-alliance/the-blue-alliance-android/issues/663

**Comment by gofirst2220** [comment]
It just gives "TBA has stopped working" and feedback button on that window does nothing. However, the app itself works fine for now. And would you add App shortcuts for Nougat App shortcuts feature?

**Comment by phil-lopreiato** [comment]
What kind of shortcuts do you want to see? I can put it on the list, but I won't make any guarantees about when they'd ship.

**Comment by gofirst2220** [comment]
App shortcuts could make it go from the drawer/ homescreen icon straight to certain parts of the app like TBA favorites section or to search. the App Shortcuts on android is like iOS 3D Touch feature.

**Comment by 1fish2** [comment]
Please say more about when & how this feature might be good for TBA users. Not having used app shortcuts, this isn't obvious except in a case where it avoids opening the app.

The user could:

1. Long-press the app icon.
2. Read the menu items.
3. Ideally, find the desired screen listed in the menu.
4. Tap that item.

Or:

1. Just tap to open the app
2. Navigate to the desired screen in the usual way.

Potentially the shortcut could save the app's time drawing intermediate screens, but it takes more user time and work. [Don't Make Me Think](https://smile.amazon.com/Dont-Make-Think-Revisited-Usability/dp/0321965515/).

Apple must have found this feature good for usability. Here's their [UI guidelines](https://developer.apple.com/ios/human-interface-guidelines/interaction/3d-touch/).
