### ISSUE TITLE
Would like to see the #RP subtotals = 2 x #wins + #ties + #40kPA + #4Rotors

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#831]
The Rankings screen shows the average Ranking Score (and the additional ranking sort order criteria) but it would help to explain that average via its subtotals: `2 x #wins + #ties + #40kPA + #4Rotors`. Of course it's just the last two factors that are not shown.

Thus it doesn't explain why these two "(6-1-0)" WLTs have different Ranking Scores:

![ranking-scores](https://cloud.githubusercontent.com/assets/1043120/24078354/7c1c1a08-0c28-11e7-82a1-1ead09f5560c.png)

Tapping "MORE" shows the same info plus the team's Last Match and Next Match. It doesn't directly show any more info on ranking but from there one can open the Matches tab, tap on a match, open the Breakdown tab, and repeat for the other played matches.

**Comment by fangeugene** [comment]
Depends on https://github.com/the-blue-alliance/the-blue-alliance/issues/1848

**Comment by bherbst** [comment]
Going to close this out - guessing not many folks are interested in more detailed 2017 breakdowns at this point and it is dependent on backend changes that never happened
