### ISSUE TITLE
Support District Championship Divisions

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#834]
MSC currently looks like this

![image](https://cloud.githubusercontent.com/assets/1421884/24888025/5907f83a-1e2e-11e7-90da-14383279a113.png)

**Comment by phil-lopreiato** [comment]
All better
![device-2017-04-12-151739](https://cloud.githubusercontent.com/assets/2754863/24975321/3a8cbde4-1f93-11e7-9d85-3c39f8a10b11.png)
