### ISSUE TITLE
Teams in the 7000s

### ISSUE THREAD

**Issue by thejwzhang** [the-blue-alliance/the-blue-alliance-android#840]
Teams in the 7000s do not show up anywhere on the app.

**Comment by 1fish2** [comment]
I think Issue #706 is getting at this same bug.

The new block of teams does show up in an event where they're registered, but you may have to force the app to reconstruct the Teams tabs strip to get a new block to appear in the Teams screen.

**Workaround:** Try switching to the Events screen and back to Teams.
Or switch to Events, switch to an older year, switch back, then switch back to Teams.

**Comment by thejwzhang** [comment]
It looks like the workaround isn't working because none of the 7000s teams are to be found on the app. For example, try the Silicon Valley Regional 2018. Team 7245 is listed as going to the event, but when clicking on it it says "No info found". On the Blue Alliance website, however, team 7245 has a page that shows their team info.

**Comment by thejwzhang** [comment]
It looks like the teams are now showing up and this was fixed. However, when going to an event and then clicking on the team, the link doesn't seem to work. For example, the Las Vegas Regional page shows team 7183 on the list of teams, but clicking on it leads you to an empty page. If you search for team 7183 on the app, however, their page comes up.
