### ISSUE TITLE
Firebase Crash Reporter shuts down Sept 8, 2018. Switch to Firebase Crashlytics

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#851]
"[Firebase Crash Reporting will continue to be functional until September 8th, 2018 - at which point it will be retired fully.](https://firebase.googleblog.com/2018/03/firebase-crashlytics-graduates-from-beta.html)" Not much advance notice, Google.

**Comment by bherbst** [comment]
This was done at some point 😆
