### ISSUE TITLE
Updates for API 27

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#852]
Does the app need updates for API 27?

Consider testing for small-memory phones:

    * test on low-memory emulators, ldpi & mdpi screens, small screens.
    * update SupportLib
    * memory profiler
    * Prop Set Size (PSS) of your app's mem usage should be < 50MB; on-device app size < 40MB

**Comment by dracco1993** [comment]
This is now irrelevant, as #880 bumped us up to version 28.

**Comment by phil-lopreiato** [comment]
Hopefully nothing major breaks, but we can file further issues as they arise
