### ISSUE TITLE
Updates to existing apps required to target API level 26+ in November 2018

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#853]
[The Play store will require API 26+ in November](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html) (unless they redefine "a recent Android API level" to 27 or 28):

> Play will require that new apps and app updates target a recent Android API level. This will be required for new apps in August 2018, and for **updates to existing apps in November 2018**.

> November 2018: Updates to existing apps required to target API level 26 or higher.

**Comment by 1fish2** [comment]
A [checklist of resources](https://developer.android.com/distribute/best-practices/develop/target-sdk.html) for help and support updating to newer Android APIs.

**Comment by phil-lopreiato** [comment]
We should be all set after https://github.com/the-blue-alliance/the-blue-alliance-android/pull/880
