### ISSUE TITLE
Updates for API 28

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#854]
[Android P API 28 is in developer preview](https://android-developers.googleblog.com/2018/03/previewing-android-p.html). Updates needed for it:

* Test on emulators with ugly display cutouts.
* Test on the updated ("faster") ART runtime.
* Be sure to avoid private APIs.

Optional:

* Use indoor positioning with Wi-Fi RTT with the pit map.
* Android P gives you an easier way to decode images to bitmaps or drawables -- [ImageDecoder](https://developer.android.com/reference/android/graphics/ImageDecoder.html), which deprecates [BitmapFactory](https://developer.android.com/reference/android/graphics/BitmapFactory.html). ... You can decode and scale to an exact size just by calling setResize() with the target dimensions. You can also call getSampledSize() to get the image dimensions at a specific sample rate, then scale to those dimensions.
* JobScheduler additions.
* Rewrite in Kotlin.

**Comment by dracco1993** [comment]
This was completed in #880.

**Comment by phil-lopreiato** [comment]
Hopefully nothing major breaks, but we can file further issues as they arise
