### ISSUE TITLE
Show Media on Team @ Event

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance-android#863]
Team @ Event is 4x more viewed than Team. Team @ Event doesn't show Media, requiring much deeper investigation to find.

We should show the Media tab in Team @ Event views.

![image](https://user-images.githubusercontent.com/57101/38213354-bc9b83f2-3675-11e8-98c8-b8734b24d09e.png)

**Comment by bherbst** [comment]
I think this is done as per #882 . Can it be closed?
