### ISSUE TITLE
App crashes on entering double quote

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#869]
From https://github.com/the-blue-alliance/the-blue-alliance/issues/2292

## Expected Behavior
App should accept quotation marks (") in the search bar to allow searching for teams including such characters (i.e. 907, 1098, etc.)

## Current Behavior
The app crashes and restarts when this occurs.

## Possible Solution
Likely, the input needs to be escaped as it is entered.

## Steps to Reproduce (for bugs)
1. Open the TBA app
2. Press the search button
3. Type in a string including the character " (\u0022)

## Your Environment
* Android 6.0.1
* App version used: 4.3.1

**Comment by bherbst** [comment]
I've been digging into this sporadically, and have discovered that SQLite FTS simply [doesn't support searching for quotes](http://sqlite.1065341.n5.nabble.com/Building-an-fts-Query-for-Double-Quote-td62541.html).

Our best option might be to just strip quotes- I'm not sure that searching for them would be the most common way to find those teams. 

We could also play with something other than FTS, but I'm not sure that's worth our effort.

FWIW, while web does show those teams in the search box's typeahead dropdown, actually executing that search will [return no results](https://www.thebluealliance.com/search?q=%22).
