### ISSUE TITLE
2018 Team Events lists don't populate

### ISSUE THREAD

**Issue by jlmcmchl** [the-blue-alliance/the-blue-alliance-android#876]
When I try to view team event lists in 2018, nothing shows up. I cleared cache and storage, but no dice. 2019 events/ teams work fine. 

Example: Team 2771, 2015-2018
Example: Team 27, 2018

Android 9, OnePlus 6

**Comment by bherbst** [comment]
I'm not able to reproduce this. Are you still seeing it @jlmcmchl ?
