### ISSUE TITLE
Match Breakdown Cutting Off Numbers

### ISSUE THREAD

**Issue by ghost** [the-blue-alliance/the-blue-alliance-android#898]
On an Android Galaxy J7 2017, the cargo ships cargo count number is cut off the screen.

**Comment by jaredhasenklein** [comment]
Can you provide a screenshot of this if it is still an issue? I'm trying to reproduce on various-sized devices and can't tell what's getting cut off.

**Comment by Hess1113** [comment]
![Screenshot_20191119-183326_The Blue Alliance](https://user-images.githubusercontent.com/25645948/69196020-4b066200-0afb-11ea-9d3b-51b14915288b.jpg)
Here is a screenshot. I have gotten a new phone and this screenshot is from a Galaxy S9.
