### ISSUE TITLE
Cannot unfavorite a team.

### ISSUE THREAD

**Issue by brennonbrimhall** [the-blue-alliance/the-blue-alliance-android#904]
Latest version of app (5.1.1).  Pixel 2.
![Screenshot_20190308-185004](https://user-images.githubusercontent.com/2270816/54062370-8eba7500-41d3-11e9-8c58-9340ae2ae031.png)

**Comment by ZachOrr** [comment]
Going to close, since we're unable to replicate. If anyone else has an issue like, this feel free to re-open, or open a new issue, and I'm more than willing to help work through what's going wrong and try to find a solution.
