### ISSUE TITLE
Feature Request: Adaptive Icon

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance-android#912]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

This will make our icon render better on more Android launchers.

**Comment by bherbst** [comment]
I've actually been working on this and soonest have it in a good place,
just need to get a better SVG of the logo. The one on GitHub has some weird
gaps.

**Comment by gregmarra** [comment]
Awesome! What are the issues with the logo on GitHub?

**Comment by bherbst** [comment]
I'm not sure if this will come through properly (on my phone right now), but there are gaps at the bottom right at three transition between the vertical side lines and the bottom half circle. They become particularly prominent in the icon.

![content://com google android googlequicksearchbox CommonContentProvider/assist com google android apps gsa staticplugins assist screenshot ScreenshotProvider/com google android apps gsa staticplugins assist screenshot ScreenshotProvider/ScreenAssistScreenshots/Screenshot_20190324-174609](https://user-images.githubusercontent.com/3267925/54887073-e7893f00-4e5c-11e9-9806-3176fdc20a29.png)

**Comment by gregmarra** [comment]
Oh hmm! Perhaps we can get someone to fix it, or you might be able to edit
it as part of this.
