### ISSUE TITLE
[Bug] No notifications on Android 9.0

### ISSUE THREAD

**Issue by Alex-BusNet** [the-blue-alliance/the-blue-alliance-android#916]
My phone (Samsung Galaxy Note 8) just updated to Android 9.0, and now I'm not recieving notifications (e.g. upcoming matches or match results) for teams I have favorited. All notifications are enabled in both TBA and Android settings. 

TBA version: 5.1.4 
Commit ID: 57d0cec

**Comment by bmirisola** [comment]
I've also been having this issue ever since week 6 ended. I was upset I missed many Michigan championship matches and now I'm missing Houston

**Comment by ZachOrr** [comment]
This should be fixed with https://github.com/the-blue-alliance/the-blue-alliance/pull/2500 and https://github.com/the-blue-alliance/the-blue-alliance-android/pull/917 - update to Android v5.1.5
