### ISSUE TITLE
Back button does not respect navigation hierarchy 

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance-android#918]
[meta: feel free to close if this is just an Android thing - we've seen this feature request quite a bit from the user survey and via social]

The back button on Android does not necessarily respect the navigation stack. For example, navigating from Events -> Event -> Team@Event, and then hitting the back button will bring you all the way back to the Events view. The back button should take you one step up the navigation hierarchy, so back to the Event view.

**Comment by bherbst** [comment]
I'm not able to reproduce this - seems to be working as expected for me
