### ISSUE TITLE
2020 events shown as offseasons incorrectly.

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance-android#930]
bug may be in https://github.com/the-blue-alliance/the-blue-alliance-android/blob/5c94e11e5640a08a3547c16646efec3f018835c8/android/src/main/java/com/thebluealliance/androidclient/Constants.java#L49

Events use that to calculate their ‘week’ on the client, per https://github.com/the-blue-alliance/the-blue-alliance-android/blob/5c94e11e5640a08a3547c16646efec3f018835c8/android/src/main/java/com/thebluealliance/androidclient/models/Event.java#L94

**Comment by ofekashery** [comment]
The issue is the event type of[ ``West Central Week 0``(2020mnwcw)](https://www.thebluealliance.com/event/2020mnwcw).
It should be Preseason, not Offseason.

**Comment by ZachOrr** [comment]
The 2020mnwcw issue specially is a server side issue - if it’s a preseason event, we need to change the event type.

**Comment by ZachOrr** [comment]
Changing `2020mnwcw` from an offseason to a preseason fixed the sorting issue.
