### ISSUE TITLE
App switches to dark theme after opening settings

### ISSUE THREAD

**Issue by ewpratten** [the-blue-alliance/the-blue-alliance-android#935]
## Issue

When opening the app, it is in light theme. I can do everything normally except opening the app settings. When i open settings, the settings screen comes up in dark theme, and after exiting settings, the entire app switches to dark theme. Closing and re-opening the app will reset the theme back to light.

## Expected behaviour

The setting screen should be the same theme as the app, and the theme should not change on re-opening the app.

## Version info
```
Application: 6.0.0
Commit: d153071
Device: Google Pixel 3a XL
Android: 10 (security patch: 1/1/2020) (google play: 30/12/2019);

-- Other --
Device theme: Light
"Smallest width" (developer setting): 508dp
```

My smallest width setting causes some apps to think my phone is a tablet

**Comment by bherbst** [comment]
I'm not able to reproduce this on a similar configuration - I suspect this ended up (accidentally?) being fixed at some point.
