### ISSUE TITLE
Stuck on welcome screen (BETA)

### ISSUE THREAD

**Issue by YairZiv5951** [the-blue-alliance/the-blue-alliance-android#960]
Hey, I have installed 'The Blue Alliance' app today from the Google Play Store and I can't get past the welcome screen
I have tried logging in, not logging in, force stop the app, phone restart.

I am running Android 11 on a One Plus 8 Pro. 

![ba3a3a82-277f-49d7-b617-a22820e92aab](https://user-images.githubusercontent.com/17926038/157312277-b2aeb88a-27f0-4f02-a828-4ec4d09f63bb.jpg)

**Comment by gregmarra** [comment]
Another report over email on a Motorola E5 running android 8.1.0 and the Blue Alliance app is on version 7.0.3

**Comment by gregmarra** [comment]
Another report in Slack on a S10+

**Comment by fovea1959** [comment]
Same problem on both of our phones. Workaround was to load 7.0.0, let it download all the data, then upgrade to 7.0.4.

**Comment by phil-lopreiato** [comment]
Yeah, there's definitely something sketchy going on here, I just can't reproduce this on any of my devices :(

Thanks for everyone's patience, and if anyone wants to help debug, let me know in slack

**Comment by phil-lopreiato** [comment]
Okay, think I figured it out! I'll push an update tonight
