### ISSUE TITLE
Setup not persisting

### ISSUE THREAD

**Issue by mostlybob** [the-blue-alliance/the-blue-alliance-android#961]
Almost every time I run the app, it forgets the previous set up, including the previous data download & linking to my Google account for myTBA.

Android version 8.0.0
LG V20 software H91820h

**Comment by phil-lopreiato** [comment]
I believe this was fixed in the newest version of the app by https://github.com/the-blue-alliance/the-blue-alliance-android/commit/c34de364bb663ff18742bf39e394ba3be6eae567; please let us know if the issue persists after updating!

**Comment by mostlybob** [comment]
@phil-lopreiato You are correct. :)

> I believe this was fixed in the newest version of the app by [c34de36](https://github.com/the-blue-alliance/the-blue-alliance-android/commit/c34de364bb663ff18742bf39e394ba3be6eae567); please let us know if the issue persists after updating!
