### ISSUE TITLE
16 x "Team 971 CC Q44 Results" notifications, 14 x "[Team 971] CC Q11 Results", ... 108 total

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#969]
Today's TBA notification history has lots of duplicate notifications and they didn't arrive in time order. Here are screenshots of the notification history, scrolling through in LIFO order, and they're still arriving while creating this PR at 10:30pm:

![TBA13](https://user-images.githubusercontent.com/1043120/192130152-64c46216-51d2-407a-9b0f-db214dfbe19d.png)
![TBA12](https://user-images.githubusercontent.com/1043120/192129713-b6048342-2dbb-44e6-bcde-7cbbe8ed5a35.png)
![TBA11](https://user-images.githubusercontent.com/1043120/192129718-57fbe0ad-6fa0-4173-986e-6716d950a440.png)
![TBA10](https://user-images.githubusercontent.com/1043120/192129719-79006175-a122-460e-b817-ec25b4bf9827.png)
![TBA9](https://user-images.githubusercontent.com/1043120/192129720-f8a650b6-efd6-4e3e-83ba-f5c754430d74.png)
![TBA8](https://user-images.githubusercontent.com/1043120/192129721-53d1e97f-dae6-46d0-9936-f13a243cfb16.png)
![TBA7](https://user-images.githubusercontent.com/1043120/192129722-9803355d-80a6-4053-a643-5184cfa5482d.png)
![TBA6](https://user-images.githubusercontent.com/1043120/192129723-9c297f36-a675-45a9-8c45-79fac96c6398.png)
![TBA5](https://user-images.githubusercontent.com/1043120/192129724-48cc628d-4e4c-438a-930d-4122b15982cb.png)
![TBA4](https://user-images.githubusercontent.com/1043120/192129725-3f97733b-42ce-4c13-82d9-497042dc972a.png)
![TBA3](https://user-images.githubusercontent.com/1043120/192129726-7b927766-83f6-494a-a94d-ec9554da5b83.png)
![TBA2](https://user-images.githubusercontent.com/1043120/192129727-44da535a-87f8-4bc4-9773-67c8bb88e101.png)
![TBA1](https://user-images.githubusercontent.com/1043120/192129728-64d4996f-ba0b-4d24-8b8b-9d5e15362e48.png)

Here's what I did:

- Install TBA (7.0.5) on a new phone (Pixel 6, Android 13), approximately during CC Q11.
- Started getting lots of duplicate notifications.
- Went to myTBA on the web and unsubscribed from everything except Team 971 {Alliance Selection, Awards Posted, Match Score, Upcoming Match} before any of my other favorite teams generated notifications.
- Made TBA notifications Silent via Android Settings since they're repeating so often.
- Saw no Upcoming Match notifications.

Edit: \#66 arrived, "Team 971 CC Q19 Results".

**Comment by 1fish2** [comment]
It's now up to 108 notifications for yesterday's matches. Today's haven't started yet.

I'll uninstall and reinstall.

**Comment by 1fish2** [comment]
Un/Reinstall didn't help.
Unsubscribing from everything and resubscribing to 971 matches didn't help.
At 9pm it was still notifying for Q19, Q31, etc.
76 notifications since reinstalling this morning, including 9 x Q44 (played yesterday), 12 for Q55, ...
Now I'm testing that staying unsubscribed from everything works.
It never showed any upcoming-match notifications.

**Comment by 1fish2** [comment]
TBA notified at 24 times yesterday and today "Team 9584 Awards", up until a few minutes ago. So far.

**Comment by ZachOrr** [comment]
Linking to https://github.com/the-blue-alliance/the-blue-alliance/issues/5668 but closing here. This is a backend issue.
