### ISSUE TITLE
App can not open a website links

### ISSUE THREAD

**Issue by arnon001** [the-blue-alliance/the-blue-alliance-android#970]
![Screenshot_20230101-072125_The Blue Alliance](https://user-images.githubusercontent.com/58848496/210161822-eb8323ea-1a1a-444c-8e0a-8bd689dfb65c.jpg)
When i click the "View Team's website" I'm getting it, no matter the team

**Comment by dracco1993** [comment]
I tried to replicate this with a local build, and it's working fine.  👀 

When I run the production build and try to replicate it, this is the line that comes back from `logcat`:
`03-06 12:57:19.773  2155  2161 I native  : I0000 00:00:1678125439.773843    2161 tf_lite_classifier.cc:383] Event stream classified as kNone`  🤔

**Comment by bherbst** [comment]
I think this was fixed but not released last year: https://github.com/the-blue-alliance/the-blue-alliance-android/pull/963

**Comment by bherbst** [comment]
Closing as fixed wtih #963
